leancloud/docs

md/cloud_code_commandline.md
md/cloud_code_guide.md

默认安装移除 sudo 命令，而是另外提示，防止 windows 用户误解。

Fixed sudo

---

md/js_guide.md
md/rest_api.md

当上下文表示 JavaScript 这门语言时，应该使用 "JavaScript"。
参考链接：[1995 年，Netscape 和 Sun 联合宣布该语言，命名为 JavaScript](https://web.archive.org/web/20070916144913/http://wp.netscape.com/newsref/pr/newsrelease67.html)。

修复 REST API 文档中的 typo

---

views/leanengine_guide.tmpl

因为 LeanEngine 使用 nunjucks 来生成多份文档的 md 文件，这一步会导致
`{{appid}}` 这样的变量直接被替换为空（因为 nunjucks 上下文没有该变量）。
现在使用一个变通的办法：在模板文件最上方先定义出来 appid 等几个变量，
其值为 '{{appid}}'。

LeanEngine: 解决 appid 等变量无法渲染的问题

---

md/js_realtime.md

js-realtime-sdk 2.2 版本文档更新，请 @wangxiao review，也请达叔看下是否有问题 @myleslee 。谢谢。
主要改动有：
- 新增加了「安装与配置」章节
- 减少了一级标题的数量
- 「兼容性」、「demo」、「文档贡献」、「GitHub 仓库地址」移至「简介」下
- 「特别说明」移至「概念」下
- 「通过 bower 安装」、「兼容」移至新的「安装与配置」下
- 替换了一些不太精确的说法
- 「IE8+」替换为「IE8 与 IE9」
- 「与其他 SDK 通讯」替换为「与其他客户端通讯」
- 修正了一些语法问题
- 修改了一些有主观色彩的措辞
- 删除了一段与 SDK 无关的 IE8 调试技巧

[js-realtime] 增加了「安装与配置」章节，调整了一些章节的组织结构。

---

Gruntfile.js
package.json

* 打包时上传 snippetVersion 和 content 的关联关系：这一步查询所有 snippetVersion 有点慢（5 秒左右，会查询到 6000+ 个 version），查询完成输出日志：
```
current snippets count: 6294
```
如果有新的 snippet 保存，会输出类似的日志：
```
save new Snippet: 由于一个用户一次登录只能加入一个聊天室，...
```
* localBuild 任务不会执行 comment 命令，防止开发阶段的 snippet 和 doc 上传。
* localBuild 任务增加 `nunjucks` 动作，使得多渲染文档能够生成 md，并最终渲染成 html
* 如果 doc 已经存在，则不再更新。之前 293 行会保存，我觉得没有必要。
* 使用 AV 自带的 promise，而不是 `Q` 组件：我们默认有 promise，而且够用，所以重写了很多逻辑。‘
@sunchanglong 麻烦 review 下。

评论插件：打包时增加 snipetContent 上传；localBuild 不执行 comment 任务

---

md/realtime_v2.md

合并对话属性和对话数据表字段的两个表格

---

views/leanengine_guide-node.md

sdjcw
2015-10-08 10:38:25
因为这个功能依赖 Node.js 的 Domain 模块，而该模块在 Node.js 4.x 不推荐使用了，所以在云引擎获取
currentUser 的机制后续会发生改变。
zhiyanglee
2015-09-09 21:46:27
为什么通常不建议、

补充不推荐使用 AV.User.current() 的原因

---

md/python_guide.md

`destroy_all` 这个方法已经不支持了，从文档中移除。

remove destroy_all document in python guide

---

md/realtime_rest_api.md

fix(docs): add url-encoded command for params

---

views/realtime_guide-android.md

查询历史记录的第二个参数，如果按照文档所写，使用getReceiptTimestamp() 则无法正确查询到历史记录，而使用getTimestamp() 就能正确查询。前者是对方收到消息的时间，后者是发送消息的时间。（2015-11-19T07:12:53.764Z by	ibookpa_tc）

fix(docs): fix a wrong param in retrieving conversation history 

---

md/start/ios_start.md

在 Run Script 中添加一个强制签名的步骤，用于动态库 SDK 的集成。 @leancloud/objective-c

Add codesign in Run Script

---

md/android_statistics.md

android.permission.READ_LOGS 漏掉了

fix(docs): 补充 Android 统计/应用权限配置的示例代码

---

md/realtime_v2.md

服务端为了兼容老版本，不得不使用了与新版本 action 不一致的字段，给用户造成了困扰，详情见工单：
故在文档和 SDK 层面做下注释说明。
iOS-SDK 也做了注释说明 ： https://github.com/leancloud/ios-sdk/pull/577

edit the annotation of  action for signature

---

md/push_guide.md

最近发现很多用户可能没有注意到要给 ios push 设置过期时间。这个可能导致 ios push 消息到达率的降低。这里修改一下文档，强调一下其重要性，并且修改一下描述。

强调 ios push 过期时间的重要性

---

md/realtime_rest_api.md

fix(docs): REST API 获取聊天记录需要 masterkey 权限

---

views/realtime_guide.tmpl

目前只有 iOS 文档对此功能提供了代码，所以这次先从主模板里去掉这句话。

fix(docs): 删除 iOS 本地缓存查询的重复语句

---

md/cloud_code_commandline.md
md/js_realtime.md
md/realtime.md
md/tool_tips.md
views/leanengine_guide-cloudcode.md
views/leanengine_guide-node.md
views/leanengine_guide-python.md
views/leanengine_guide.tmpl

issue https://github.com/leancloud/cloud-code/issues/481
我把找到的 `avosapps.com` 的地方都换成了 `leanapp.cn`。
另外把 `xxx.avosapps.com` 这类说明都改成了 `${your_app_domain}.leanapp.cn`，因为 xxx 看起来有点尴尬。。

更新云引擎的二级域名

---

md/cloud_code_faq.md

最好能在 leanengine_guide 文档上给个链接，但是我发现 leanengine_guide 文档已经没有 Hook 函数 这个专门的小节，而是和 Cloud 函数合并起来了。。。。所以我不知道加在哪里合适。

LeanEngine: issue #463 增加 hook 函数可能造成死循环调用的 FAQ 说明

---

md/start/android_start.md

根据支持顾问反馈，这种方法容易引起误解，所以初始化方法只保留 AVOSCloud.initialize 一种。

fix(docs): 删除使用 Activity 来初始化 Android SDK 的方法

---

md/python_guide.md

The correct startswith was written as 'start_with' or 'starts_with' in the document, causing confusion during development.

Fix startswith 's  typo

---

md/js_guide.md

用户评论：`var query = new AV.Query(Post);` 报错，只有给 Post 加上引号才通过。

fix(docs): 修复 AV.Query 初始化的语法

---

md/push_guide.md

有反馈我们在 badge 的说明上用了引号所以会错觉为字符串

强调 badge 是数字类型

---

md/start/js_start.md

Closes #971
目前快速指南 Start 与安装指南有较多重复内容，docs 2.0 会保留安装文档，快速指南内容以后会变。

fix(docs): JS 快速指南-增加节点切换代码

---

md/realtime_rest_api.md

多次遇到用户反馈说获取聊天记录的接口不知道怎么传参数，考虑添加个例子进行说明。

给获取聊天记录的接口添加传参数示例

---

custom/less/section-docs.less

用在文档正文中。使用 `<u>` 来标注，默认的 underline 效果不理想。

feat(style): 增加自定义下划线样式，与加粗交替使用

---

md/ios_push_guide.md

ios 推送文档中一处失败链接修正

---

templates/include/header.html
views/leanengine_cloudfunction_guide-node.md
views/leanengine_cloudfunction_guide.tmpl

* 撤下菜单中 [旧版云引擎环境] 和 [云引擎 2.0 升级 3.0 指南] 的链接
* 将 JavaScript 的代码调整为两个空格缩进，`req, res` 的变量命名调整为 `request, response`
* 细化 Request 和 Response 对象上的属性
* 补充 AV.Cloud.run 的 remote 参数
* 在实例代码的所有 Promise 加上 `.catch(console.error)`
* beforeSave/afterSave 的描述中强调是在创建对象时发生，beforeUpdate/afterUpdate 的描述中强调是在修改已有对象时发生
* 移除有关 cloudcode2 的内容（`AV.Cloud.setInterval` 和 `AV.Cloud.cronjob`）
* 免费版云引擎应用没有预备环境
@sdjcw

[云函数开发指南 · Node.js] 细节修改

---

md/leanengine_quickstart.md
views/leanengine_webhosting_guide-node.md
views/leanengine_webhosting_guide.tmpl

* 更新有关「免费版没有预备环境」的描述
* 调整段落顺序，「绑定独立域名」移到最后，「修改 Node.js」版本前移，「设置域名」前移到「部署」之后。
* 修正 Markdown 的格式（表示粗体的星号前后需要有空格）
* `app.use(AV.Cloud)` 改 `app.use(AV.express())`、修改 JS SDK 的初始化方式（Node SDK 1.x）
* 按照 Node SDK 1.x 的情况更新「处理用户登录和登出」小节
* 「健康检查」一节补充对 `/1.1/_ops/functions/metadatas` 的介绍
* `LC_` 开头的环境变量改 `LEANCLOUD_`
* 移除 `AV.Cloud.httpRequest` 的介绍，改成一个 request 的示例
* 「不建议使用 MemoryStore」的描述移到「自定义 session」小节
* 删除「Git 部署」一节中的截图，不再详细介绍 CSDN 和 GitHub 的界面，改推荐 Coding 和 OSChina 这两个国内托管，建议对于公开项目使用 https 链接。

[网站托管开发指南 · Node.js] 大量细节修改

---

md/realtime_guide-js.md

前者容易与 https://github.com/leancloud/docs/blob/dbaff34b2eddff42d2b431cd8bba68acd0e5d110/md/realtime_v2.md#离线推送通知 混淆
cc @nicecui

fix(js-realtime): 将「离线消息推送」重命名为「离线消息内容通知」

---

Gruntfile.js

文档本身有 id 的是 h1 这类 dom，还有超级链接。
p 和 pre 默认没有 id，所以赋值应该问题不大。

feat: 可以评论的文档片段（p 和 pre) 增加 id 属性，方便控制台通过锚点跳转

---

md/start/ios_start.md

修正 iOS SDK 快速入门中错误的 deployment target。这里特意把 Xcode 的说明删除了，因为跟 Xcode 版本没有关联。 @leancloud/docs-editor

Fix wrong deployment target for iOS SDK

---

templates/pages/faq_list.html
views/realtime_guide-ios.md

Closes #1292
这个链接没有失效，一是在文档最后，屏幕滚动受限视觉上定位不明显，二是没有在地址栏中显示其 # 值。

fix(docs): [存储] iOS 为链接增加 ID 符合 HTML5 标准

---

md/leanengine_quickstart.md

删除了 `$` 符号，因为很多用户会直接复制粘贴，还有 win 用户不是这个提示符。
php 的 `/` 路由还未完成，后续补充。

LeanEngine: 添加 Python 和 PHP 的快速入门 tab 块

---

md/leancache_guide.md
md/leanengine_examples.md

同时删去了 `（例如 V8 的 Array 实际上是通过 Hash Map 实现的）` 这句话，这本来是我回复在论坛上的，写在这里可能过于细节了，用户并不关心这个。

添加 lean-cache-demos 的链接

---

md/push_guide.md

混合推送之后会属于收费功能，增加了一个选项做权限控制，需要用户点击一下才能开始试用混合推送功能。这里增加说明。

混合推送增加权限控制说明

---

templates/include/header.html

fix(docs): [nav] 去掉 iOS 测试分发链接

---

views/leanengine_faq.md
views/leanengine_webhosting_guide-java.md
views/leanengine_webhosting_guide-node.md
views/leanengine_webhosting_guide-php.md
views/leanengine_webhosting_guide.tmpl
views/tool_tips.md

主要是修改了网站托管的模板和 Node.js 的实现；对 PHP 和 Java 的修改仅为了适应模板的修改，并没有实质性修改。
修改包括：
* 重排小标题，减少小标题层级，在 Node.js 页面默认展开所有小标题
* 移动「GitLab 部署常见问题」到 FAQ 页面
* 更新有关项目结构、健康检查部分的描述
* 精简对时区问题的描述
* 补充 LeanCahce 示例、Koa 示例

[云引擎] 重构 Node.js 网站托管指南

---

views/sdk_setup-ios.md
views/start/ios_start.md

更新 Objective-C SDK 的安装文档，主要增加了手动编译 framework 的步骤，并增加了 checkout 某个版本的命令。 
@leancloud/docs-editor 快速入门这个页面的标题好像有点小。
@nicecui 对应 [objc-sdk/#34](https://github.com/leancloud/objc-sdk/issues/34) 这个 issue。
@leancloud/ios-group

Update installation doc

---

views/leanstorage_guide.tmpl

fix(docs): [存储] _User 表默认关闭 find 权限的目的是为了限制登录用户查询到其他用户的数据

---

views/realtime_guide-objc.md
views/realtime_guide.tmpl

新增示例以查询自己参与过的所有对话，包括系统对话。取代 PR #1740 。
之前有用户对 ConversationQuery 默认不返回系统对话有疑惑，因此在文档中描述一下。请其他 SDK 也补充一下示例代码。在各自的实时通信文档中新建名为 conversation_query_all_include_system 的 block 即可。
@leeyeh @daweibayu @leancloud/sdker

Add example for querying all conversations include system

---

views/leanstorage_guide-python.md

用户评论：2017-03-08T14:19:06.285Z	Trojx
query.equal_to('reminders', [reminder1, reminder2])
这种查询方法,reminder1与reminder2的顺序不能调换,否则不符合条件,查询无结果
@aisk

fix: [Python] 注明 equal_to 和 contains_all 的区别

---

custom/js/app.js
views/_helper.md
views/_helper.njk
views/weapp.md

add `{% import "views/_helper.njk" as docs %}` to the first line of
.md/.tmpl
then use `{{ docs.mustache(‘var’,’’,’’,true) }}`
output: `{{mustache(‘var’)}}` which will be rendered by Angular as
`{{var}}`

chore: correctly display {{var}} in code sample

---

views/realtime_v2.md

fix: iOS/WP 离线消息推送的过期时间 7 天

---

views/app_search_guide.md

自定义词库大小限制修改为 512K，原来 64K 实用性不够。

(fix)自定义词库大小限制为 512K

---

templates/include/common-footer.html

fix: 评论展现时使用创建时间，而不是修改时间

---

views/ios_push_guide.md

iOS SDK 的 AVInstallation 中没有定义这两个属性，从文档中去掉。 @myleslee

Remove undefined installation properties

---

views/realtime_guide.tmpl

删除一个关于未读消息数的错误描述。
开启未读消息数时，即使在线收到消息，未读消息数量也会增加。也要求用户在合适的时机调用 conversation.read() 方法来重置未读消息数。
@ylgrgyq @myleslee

Remove a wrong description for unread notification

---

views/android_push_guide.md

fix: [推送] Android - 去掉 GCM 只出现在美国文档中的限制

---

views/realtime_guide-objc.md

更新开启 IM 未读通知的示例代码，用新的接口取代已废弃的接口。 @myleslee

Update code snippet for enabling unread notification

---

views/realtime_guide-js.md

修复了一个拼写错误
在新的群聊已读回执方案发布前，先去掉现在的。

feat: 暂时去掉 JS 群聊已读部分

---

views/realtime_guide-android.md
views/realtime_guide-objc.md
views/realtime_guide.tmpl

Closes https://github.com/leancloud/paas/issues/964

fix: [IM] iOS 离线消息推送通知并不是默认关闭的

---

views/realtime_guide-objc.md

适配最新 SDK
用 typedef NSString * const AVIMSignatureAction 替换 NSString * 类型。
虽然参数类型变了，但没有兼容问题，都是 NSString * 类型。

Update AVIMSignature action

---

views/sdk_setup-objc.md

美国节点需单独设置 `AVServiceRegionUS`，在安装指南中需突出说明。原文档以注释的形式显示容易被忽略。
来自工单反馈： https://leanticket.cn/tickets/17500

make ServiceRegion stand out

---

views/android_push_guide.md

文档对 Channel ID 的说明链接地址有误，替换为正确的。

Replace channelId URL

---

views/realtime_v2.md

主要是离线推送还支持 Android，不只是 iOS 了。
控制台的修改提了 [issue](https://github.com/leancloud/avfr/issues/1601)，后续会改掉。

修改一下实时通信离线消息推送的说明

---

views/android_mixpush_guide.md

Change absolute linking to relative linking,
to fix 404 in production environment.
resolve #2828

android mixpush: fix image link

---

comment.js
custom/less/bootstrap/code.less
custom/less/section-docs.less
custom/less/theme-core.less

因为代码容器 pre 需要横向滚动，原评论指示器不再能显示，因此去掉代码的评论功能

fix: 移除代码换行的样式

---

deploy.sh

shell glob will  not be parsed inside double quotes.

chore(jenkins): fix quotes.

---

views/leanengine_cli.md

由于文档站点换用了 algolia，`lean search` 已失效。
新版的 lean-cli 将移除这一命令（lean-cli#414）。

:fix: (lean-cli) 移除 lean search

---

views/chatkit-ios.md
views/realtime-guide-beginner.md
views/realtime-guide-senior.md

- 新版的 rtm 指南大部分地方都已经指定了 unique 参数，
这个 pr 补充了少数几处 js/objc/c# 未指定的代码示例，并补充了现各 SDK 默认值的说明。
- 新版的 Java SDK 已默认启用了 unique。
- REST API 已在 #2874 中修改。
resolve #2858

创建 conversation 时指定 unique 参数为真

---

views/acl-guide.md

Unlike in objc sdk, `getRoles()` in js sdk returns a Relation,
not an array.
The same applies to swift sdk.
This commit also updates the related swift sample with new sdk API.

fix(acl): getRoles return type for js & swift.

---

views/realtime-guide-senior.md

- Since `signature_ts` is equvilent to `timestamp`,
just use `timestamp` here to avoid confusing readres.
- There is no `signature` param.

fix(rtm): get log signature description

---

views/leandb_mysql_guide.md

The second usage of environment variable `MYSQL_HOST_MYRDB`
should be replaced with `MYSQL_PORT_MYRDB` instead.

fix(mysql): typo in php sample

---

views/status_system.md

Previously, some code sample used "dennis"/"dennis id"
in objectId of user pointer,
which may confuses readers to fill in `username`
(also called user id in some context).

fix(status): curl code sample

---

views/leanengine_webhosting_guide-python.md

Unedr LeanEngine's staging environment,
`LEANCLOUD_APP_ENV` (used by python sdk) is `stage`, not `staging`.
`staging` is the value of `NODE_ENV`,
used by nodejs sdk.

fix(leanengine): LEANCLOUD_APP_ENV value

---

views/leanengine_cloudfunction_guide-python.md

I guess the sample code is edited based on python-sdk unit tests.
This statement is copied from unit tests,
and was forgotten to delete.

fix(python): typo in before_update hook definition

---

views/realtime-guide-intermediate.md

close #2928
partially implemented 的意思是因敏感词过滤等原因消息修改后会通知发送者（这是由 RTM API 提供的能力），但 SDK 没有封装 RTM API 给的 PatchReason

PatchReason on recalled/updated message

---

views/leandb_mysql_guide.md

Add an example of connecting to LeanDB mysql in Python,
use MySQL's official python driver.
I tested the code sample in following procedures:
1. Setup a LeanEngine python project via `lean-cli` (select `flask` template) and enable a mysql instance at dashboard.
2. Add `mysql-connector-python` to project `requirements.txt`.
3. In `app.py`, define a new function:
```python
@app.route('/mysql')
def connect_to_mysql():
return result
```
4. Deploy it with `lean deploy` and check https://YOURSUBDOMAIN.leanapp.cn/mysql:
The solution is 2

feat(LeanDB): mysql python sample

---

views/rest_api.md

Previously, `,master` postfix was only mentioned in `X-LC-Sign` section.
A lot of developers who does not want to use this `X-LC-Sign` feature 
may skip the whole section.
Later when they read about `{{masterkey}},master` in other sections may 
feel confused.
related support ticket: 20573

feat(rest): describe `,master` for X-LC-Key

---

views/leancache_guide.md

ioredis has a more friendly API and default promise support.
leanengine-nodejs-demos already use ioredis.
close #3065

feat(LeanCache): replace node_redis with ioredis

---

views/leanengine_webhosting_guide-node.md

npm is agnostic about which registry you used to generate the package-lock.json
since 5.0.0 shipped with Node.js 8.0 [0].
And LeanEngine only uses `package-lock.json` for Node.js 8.0+.
But yarn still depends on the registry host in yarn.lock [1].
[0]: https://stackoverflow.com/questions/53814967/what-is-the-point-of-having-resolved-url-in-package-lock-json
[1]: https://github.com/yarnpkg/yarn/issues/5892

fix(LeanEngine):only yarn.lock has slow conn issue

---

views/leanengine_cloudfunction_guide-node.md
views/leanengine_cloudfunction_guide-php.md

according to leancloud/leanengine-node-sdk
74d167636d5f77b949cf131c2d9dc9651fd77812

fix(LeanEngine): typo

---

views/leanengine_cloudfunction_guide-node.md

clarify cloud function online editing cannot import non-builtin modules.
related ticket: 21118

fix(LeanEngine):online edit cannot use custom deps

---

templates/include/doc-nav.html
templates/include/header.html
templates/layouts/template.swig

文档内导航的作用是帮助用户快速找到一个页面/小节，并非相关页面/小节的唯一入口。隐藏导航因解决「进入一篇文档时可视区域内大部分都是导航」和「页面滚动时因为导航的伸缩而跳来跳去」这两个痛点所带来的优势应该是可以弥补缺少 shortcuts 所带来的缺陷的。
close #1712

fix(UI): hide unnecessary elements on mobile

---

Gruntfile.js
views/custom-api-domain-guide.md
views/leanengine-rest-api.md
views/rest_api.md
views/sdk_setup.tmpl

- prepare for future changes (prefer custom api domain)
- more compatible with zh-docs.leancloud.app

feat(rest): describe base url

---

views/rest_sms_api.md
views/sms-guide.md

Use `{{{var}}}` instead of `{{var}}`
to avoid Handlebars HTML encoding special characters such as & and <.
related forum post: https://forum.avoscloud.com/t/amp/3276

fix(sms): sms template syntax

---

views/leanstorage_guide.tmpl

fix: cn-e1 supported thumbnails long long ago.

---

views/leanengine_webhosting_guide.tmpl

12.x is the current LTS version of node.js

feat: engines.node recommend 12.x instead of 10.x

---

views/leancache_guide.md

Some users may mistakenly preserve `<>`
when replacing with their own values.
Related ticket 21676

fix: avoid use `<>` in code sample

---

views/leanengine_cloudfunction_guide.tmpl

Unlike other SDKs, Java has two seperated hook functions for onVerified:
- onVerifiedSMS
- onVerifiedEmail
Thank 517259854 for bringing this matter to our attention.

fix(java): wrong cloud functino name

---

views/sdk_setup.tmpl

The platform selector is missing,
possibly caused by git merging.
Thanks [sysOrange] for bringing this to our attention.
[sysOrange]: https://forum.leancloud.cn/t/cocos-js/22714

fix: js sdk setup regression

---

views/sdk_setup-android.md

1. This has been merged into sdk_setup-java
2. Currently https://leancloud.cn/docs/sdk_setup-android.html is broken
Thanks wxjz for bringing this to our attention.

feat(storage): remove android setup guide

---

views/leanstorage_guide.tmpl

`07:60` is invalid.
Also be consistent with code samples in other languages.
see also leancloud/docs-en#202

fix(flutter): typo in code sample

---

views/leanengine_webhosting_guide.tmpl

Now all LeanEngine instances has one cpu
(except for legacy ones).

fix(engine): remove LEANCLOUD_AVAILABLE_CPUS

---

views/leanengine_webhosting_guide.tmpl

php 7.0 support ended on 3 December 2018.

fix(engine): update php version

---

views/leanengine_cloudfunction_guide.tmpl

The type of `params` argument of callRPCWithCacheInBackground is
`@NotNull java.util.Map<String, Object>`,
which is incompatible with Map<String, String>

fix(java): callRPCWithCacheInBackground type error

---

views/realtime-guide-systemconv.md

This field is an implementation detail
and we do not need to mention it in documentation.
Also, recent SDKs use hook key instead.

fix(engine): remove `__sign`

---

views/realtime-guide-systemconv.md
views/realtime_v2.md

This demo is not maintained anymore:
- There is no leanchat-android repository under the leancloud organization.
- The latest commit of lzwjava/leanchat-android is on Sep. 5, 2015.
Thank 1063271662 for bringing this to our attention.

feat: remove leanchat-android demo link

---

views/sdk_setup.tmpl

Not all LeanCloud servers support ping.
see also #3707

feat: use curl instead of ping to test network

---

views/leaderboard-rest-api.md

已经[不能](https://github.com/leancloud/uluru-platform/blob/6dad8b8332e8327d8041679a4efae7d2f3ad303a/play-leaderboard/src/leaderboard/boards.clj#L60)更新 `order` 属性了

fix(leaderboard): cannot update order anymore

---

views/leanstorage_guide.tmpl

`blockingSubscribe` keeps code sample short
but may confuse some users not familiar with rxjava.
related ticket [23788], [20785], [23531], etc.
[23788]: https://forum.leancloud.cn/t/android/23788
[20785]: https://forum.leancloud.cn/t/android-sms-3-1/20785/33
[23531]: https://forum.leancloud.cn/t/java/23531

chore(java): change blockingSubscribe to subscribe

---

views/leanengine_cloudfunction_guide.tmpl

Cloud::start is for projects dedicated to cloud functions.
related ticket: 36796

feat(php): emphasize Cloud::start use case

---

views/rest_api.md
views/tool_tips.md

It is absent in new dashboard and old dashboard will be redirected
very soon.

feat: apionlinetest is unavailable now

---

custom/js/md.js

dn-experiments.qbox.me is a github avator proxy service by @sparanoid
which is unavailable now
(`{"error":"no such domain"}` returned by qiniu)

build: remove github avatar proxy

---

views/leanengine_webhosting_guide.tmpl

Also, spring boot template project now supports Java 11
(see also leancloud/spring-boot-getting-started#7)

feat(engine): use Java 11 by default now

---

views/acl-guide.md

The original sample throws as `AV.Role` requires ACL to init now.

fix: simplify a JS ACL sample

---

templates/pages/index.html

现在文档没有推送 REST API 文档的入口了。
我把首页地址由链接： https://leancloud.cn/docs//push_guide.html#hash978195304  改成直接跳转到 REST API 文档：

fix push-rest-api url

---

custom/js/demo.js

BallBattle 原链接失效，更换为 https://github.com/leancloud/BallBattle-Cocos

fix: update BallBattle url

---

custom/js/demo.js

「猜拳游戏」原链接对应的应用并没有部署，因而点进去只会显示「应用无响应」，替换为 github 链接。

fix: update demo url

---

views/leanstorage_friendship_guide.md

一行示例代码写错了。
`@(true)` 等同于 JSON 中的数字 `1`，`@YES` 才等同于 JSON 中的 `true`。

fix(objc): leanstorage friendship guide

---

views/leaderboard-rest-api.md

查询用户成绩的时候，不再支持 selectKeys 和 includeKeys，同时不需要 masterKey 也不需要登录就可以查用户的成绩。

remove selectKeys and includeKeys from user statistics.

---

views/leaderboard-rest-api.md

查询 object 成绩的时候，不再支持 selectKeys 和 includeKeys。

(feat) remove selectKeys and includeKeys from object statistics.

---

views/realtime-faq.md
views/realtime-guide-beginner.md
views/sdk_setup.tmpl
views/weapp.md

leancloud-realtime-plugin-typed-messages 发布了 4.0 ，解决由于插件内部使用的 SDK 与用户使用的 SDK 不匹配而导致的类型（AV.File，AV.GeoPoint）不匹配的问题。
~~改文档的过程中发现富媒体消息插件的 umd 命名空间也是 AV ，导致从 CDN 导入会覆盖整个 AV（富媒体插件只导出了一个函数），这个问题还没想好咋解决，所以 CDN 导入的部分还是使用 v3.1.0 。~~

feat(js/im): typed messages plugin v4

---

views/leanstorage_guide.tmpl

Thank 沉寂 for bringing this to our attention.

fix: Go: set user attributes need auth option

---

views/android_mixpush_guide.md

delete unnecessary permissions

---

views/realtime_rest_api_v2.md

更新即时通讯 REST API 文档增加 [临时禁言和永久禁言] 一节，之前永久禁言放到 [对话权限] 一节中似乎不妥，找起来不太方便。
现在把它单独移出来，并与临时禁言一起放到单独一节中。

更新即时通讯 REST API 文档增加 [临时禁言和永久禁言] 一节
