leancloud/docs

rest_api.md
=> Added doc for POST /rtm/messages

unity_guide.md
=> 修改Unity 初始化的方法。

android_guide.md, push_guide.md
[AndroidSDK 项目里的 issues#127] (https://github.com/leancloud/AndroidSDK/issues/127)
@lbt05
=> remove section about replace Parse to AV

push_guide.md
=> iOS badge clear 更新

dotnet_guide.md
=> wp doc updated.

unity_statistics.md
=> unity 1.1.8 doc

push_guide.md
增加推送问题排查文档
@ufosky @lbt05 @sunng87 请帮忙 review
=> Added troubleshooting for push

ios_os_x_guide.md
Apple官方文档中的对**方法**的引用格式是 
`methodName:methodName2:`
method后加半角冒号，不加空格，所以本文也采用相同格式，如：
`incrementKey:byAmount:`
=>  Revision Part 1: 更新至「对象 - 删除对象」部分

md/js_guide.md
增加 `promise` 说明，适配 js sdk v0.5.0 的发布，暂时不合并，请先帮忙 review
@aisk @wangxiao
=> Improve promiss in js guide.

md/android_guide.md, md/dotnet_guide.md, md/ios_os_x_guide.md, md/js_guide.md, md/unity_guide.md, templates/pages/sdk_down.html
链接到 leancloud-demos 项目
@killme2008
=> 更改 Demos 链接

md/ios_realtime_v2.md, md/realtime_v2.md
=> modify ios realtime v2 guide

templates/pages/index.html
=> Moved link.

md/rest_api.md
=> msg log exclusive cursor: max_ts

md/android_realtime_v2.md
=> add android realtime v2 guide

md/ios_realtime_v2.md
=> add more sample code, add open conversation

md/android_realtime_v2.md, md/realtime_v2.md
=> modify android guide bcz code change, add transient conversation sample

md/ios_os_x_guide.md
统一使用「账户」（http://www.zhihu.com/question/19609342?rf=19978236）
=> Revision Part 4 - 更新完毕

md/realtime_v2.md, templates/include/header.html, templates/pages/index.html
=> add more links to page

md/error_code.md, templates/pages/index.html
=> Improved error code

md/ios_os_x_guide.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/leancloud/docs/162)
=> Fix double code-quote.

md/android_realtime_v2.md
=> add more sample code

md/rest_api.md
https://ticket.avosapps.com/tickets/550b9fbae4b03b191311d2b3/threads
=> 增加聊天记录返回字段说明

md/android_realtime_v2.md, md/ios_realtime_v2.md
=> add more sample code for ios realtime guide

md/python_guide.md
fix https://github.com/leancloud/python-sdk/issues/20
=> update python guide for user ticket

md/sns.md
=> update sns doc for weibo sdk 3.0

md/wp_realtime_v2.md, templates/include/header.html, templates/pages/index.html
update nav bar and index html for WP realtime sdks v2.
=> update nav bar and index html for WP realtime sdks v2.

md/unity_guide.md
=> unity 5.0 bug fix.

md/start/ios_start.md
=> 增加 pod 'AVOSCloudIM'，去掉 pod 'AVOSCloudUI'

md/cloud_code_guide.md
添加域名备案前置条件
添加第5项域名备案所需资料
有个小笔误的修改
=> 添加域名备案前置条件和资料

md/realtime_rest_api.md
=> fix im REST sample

md/start/ios_start.md
添加了通过 LeanCloud Gem 集成 iOS SDK 的文档
=> Add LeanCloud Gem document for iOS integration

md/unity_guide.md
fix format for code for Unity doc.
=> fix format for code.

md/start/ios_start.md
=> Move LeanCloud Gem guide to top

md/cloud_code_commandline.md, md/cloud_code_guide.md
提示 windows 用户必须安装 node.js 在 c 盘，顺便修复 git 仓库错误。
=> Added note for windows user

md/android_push_guide.md
=> (fix) 增加启动推送服务必选步骤的说明

md/unity_guide.md
=> unity revision part 1

templates/pages/index.html
a error on nav url to dotnet api doc.
=> a error on nav url to dotnet api doc.

md/android_faq.md
=> add us cluster tutorial to android faq. fixed #267

md/android_guide.md
=> fix avuser query sample

md/android_guide.md
gradle添加dependency这部分不应该让大家一起维护，你们应该发布新版的时候就一起把这些版本号给更新了。Android studio也是不建议使用在添加dependency的时候使用`+`。一点意见，希望你们引起重视。
=> update dependencies' version

md/android_guide.md
=> replace maven last version by +

md/cloud_code_guide.md, templates/include/header.html, templates/pages/index.html
=> [云代码] 调整 HTTP 请求的文档位置和小标题。

md/realtime_v2.md
=> 增加 Simple Chat 链接

md/data_security.md
=> 添加 csv 导入 Pointer 说明。

md/ios_os_x_sms_guide.md
=> 修正 verifySmsCode 函数错误

md/js_realtime.md
=> [JS 实时通信] 增加暂态对话的说明。

views/leanengine_guide-cloudcode.md
=> 修改 Web Hosting 标题引用链接

md/dotnet_guide.md, md/dotnet_realtime.md, templates/include/header.html, templates/pages/index.html
1.update dotnet doc title
2.update cloud code nav url and text
=> rename doc and fix url.

md/python_guide.md
=> 无法通过`User.login`进行登录

md/ios_os_x_guide.md, md/ios_os_x_sms_guide.md
=> 增加 Demo 链接

md/tool_tips.md
=> 更新添加索引的文档, http://v2ex.com/t/197898

md/ios_realtime_v2.md
=> Fix document of messages query api

md/ios_os_x_guide.md
=> Add reserved word

md/start/ios_start.md
该 PR 为手动集成 iOS SDK 添加了一个缺失的步骤。
=> Add the missing step for manually integrate ios sdk

md/cloud_code_commandline.md
=> 更新命令行工具在 windows 平台的安装问题

md/android_guide.md, md/android_push_guide.md, md/android_realtime_v2.md
另外，由于增加了服务间相互启动的代码，需要用户将pushService标记为exproted=true
=> AVObject支持Parcelable接口的文档说明

md/android_realtime_v2.md, md/ios_realtime_v2.md
=> change realtime demo for ios/android

md/oauth2_provider.md, views/leanengine_guide-cloudcode.md, views/leanengine_guide-node.md, views/leanengine_guide.tmpl
=> Leanengine ping

md/android_guide.md
@myleslee 先把 android guide 改一遍，review 过后复用到其他模块。
=> change sample code in android guide

md/bigquery_guide.md
离线分析指南增加云代码和 js sdk 的支持说明。
@debugger87 也帮忙看下。
=> Big query guide

md/js_guide.md
=> 添加 underscore 类库说明

md/js_guide.md
=> modify samplecode of js guide(only for leanstorage)

md/feedback.md
=> Update feedback module's document

md/android_guide.md
=> fix android sample code error for createdAt compare

md/realtime_v2.md
=> (doc) force 参数

md/rest_api.md
=> change sample code for rest api, part 1

md/rest_api.md
=> change sample code for rest api, part 2

.gitignore, server_public/js/main.js
=> 增加 react 编译后的 js 到目标目录

md/ios_crashreporting_guide.md
=> Add server region option

views/realtime_guide.tmpl
duplicate location message block.
=> duplicate location message block.

md/faq.md
=> Update iOS faq for supporting CocoaPods

md/js_realtime.md
https://github.com/leancloud/docs/pull/426#discussion_r35611821
=> [js-realtime] Add a missing link.

md/android_realtime_v2.md
=> change Exception param to AVIMException for im

md/android_push_guide.md
=> custom receiver should not be exported for security concern in feedback from customer

md/android_guide.md
=> fix avuser query generic type

md/start/ios_start.md
=> Update ios quick start document

md/ios_os_x_faq.md, md/ios_os_x_guide.md
=> iOS：增加 batch 操作的 api 、BOOL 类型说明

md/android_guide.md
因为最近我给 https://github.com/leancloud/LeanStorageDemo-Android 加了很多 Demo 例子，希望开发者能更便捷地找到这个项目。
@myleslee
=> 增加 LeanStorageDemo-Android 链接

md/android_realtime_v2.md, md/ios_realtime_v2.md
=> 增加对话查询默认返回结果数

md/rest_api.md
=> Added date api

md/ios_os_x_guide.md
=> Change iOS cache policy name prefix

md/ios_os_x_guide.md, md/ios_realtime_v2.md
声明创建对话应该在 AVIMClient 成功打开之后。 ref https://github.com/leancloud/docs/issues/485
@myleslee
=> Refine realtime doc

md/ios_realtime_v2.md
在使用 IM 模块前，导入 IM 模块。 ref: https://github.com/leancloud/docs/issues/483
@myleslee @jwfing
=> Import IM module before using IM

md/ios_realtime_v2.md
=> Add unread document

views/leanengine_guide-cloudcode.md
=> Fixed a broken link

Gruntfile.js
=> 评论插件：段落内容为空是，不保存段落

custom/js/app.js
https://forum.leancloud.cn/t/rest-api-master/2992
=> [fix] Add missing masterkey in code blocks

templates/include/header.html, templates/pages/index.html
=> update realtime link to latest version

md/start/ios_start.md
=> State bitcode for Xcode 7

md/sns.md
=> SNS 模块 iOS 9 适配

md/push_guide.md
这块文档过期了，更新一下。
@killme2008 @sunng87  烦请帮忙 review
=> 修改推送服务关于 “Installation 自动过期和清理” 的描述

templates/include/header.html, templates/pages/index.html
1.更新文档连接描述，「规范」-> 「指南」。
2.在云引擎里面添加连接指向 云引擎 ACL 使用指南。
=> 更新文档连接描述，「规范」-> 「指南」。

md/status_system.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/leancloud/docs/565)
=> Fix inconsistent naming in examples.

templates/include/header.html, templates/pages/index.html
=> 文档合并的时候鬼使神差的聊天的链接错了，现已修复。

views/realtime_guide-android.md, views/realtime_guide-ios.md, views/realtime_guide.tmpl
=> add isUnique parameter doc for AVIMClient.createConversation

md/android_push_guide.md
添加 android.net.conn.CONNECTIVITY_CHANGE，接收网络状态发生变化时发出的 intent
=> add android.net.conn.CONNECTIVITY_CHANGE

md/ios_os_x_guide.md
用户留言：
2015-10-07T14:43:54.516Z	虎猫儿	
NSLocationWhenInUseUsageDescription 或 NSLocationWhenInUseUsageDescription 。。。。写错了吧
=> Fixed duplicate location key names for info.plist

views/leanengine_guide-node.md
用户留言：
2015-10-03T10:03:33.140Z
{wonder}
nam server.js 写错了吧？应该是node server.js
=> Fixed the command that starts server

views/realtime_guide-ios.md
跟进 #509 Import IM module before using IM
=> 增加导入 IM 模块说明

md/start/ios_start.md
=> Fix typo of quick start guidance of iOS SDK

md/ios_os_x_guide.md, md/start/ios_start.md
=> Use linker flag instead of dylib and tbz

md/sns.md
=> add LeanCloudSocialDynamic podspec install tips

views/acl_guide-android.md, views/acl_guide-ios.md, views/acl_guide-js.md
=> 修复文档跳转地址错误。

md/js_guide.md
=> Fixed example in js guide.

md/status_system.md
服务器支持重复关注，不会报错。这里删除遗留代码。
@myleslee
=> Remove legacy code

md/start/ios_start.md
=> Remove bitcode unsupported statement

views/leanengine_guide-node.md, views/leanengine_guide-python.md
=> ssh 的仓库地址需要有 GitHub 账号并配置私钥，https 的则不需要

md/android_guide.md
=> update download dependecy

views/realtime_guide-ios.md
=> Fix gem source of taobao

md/ios_os_x_guide.md
@leancloud/objective-c @myleslee
=> AVUser 子类化说明

md/cql_guide.md
=> CQL 增加 min 说明。

views/leanengine_guide-cloudcode.md, views/leanengine_guide-node.md, views/leanengine_guide.tmpl
需要等待 https://github.com/leancloud/leanengine-node-sdk/pull/31 合并并发布
=> 添加关于 leanengine-node-sdk 的 beforeUpdate 的介绍

app.json, package.json
试用了一下 heroku 的 review apps 功能，自动部署 pr，还蛮好用的。
效果点这里：https://github.com/leeyeh/docs/pull/1
=> Use heroku to preview PR.

md/js_realtime.md
包括：invited、membersjoined、kicked、membersleft
=> 为 js-realtime 的新事件添加说明

md/js_guide.md
this is the correct commit to keep.
=> Revision 1: Fixed typos, wording and formatting

archive/js_guide_collection.md
Saved a copy of js_guide.md (renamed to js_guide_collection.md) in the /archive folder just in case.
=> Remove Collection from JS guide

md/start/js_start.md
=> [js-quickstart] 在 package.json 中指定 SDK 版本。

custom/js/md.js, custom/less/section-docs.less
shoud fix https://github.com/leancloud/docs/issues/580
=> feat: basic contributor list support

md/android_guide.md
=> Android: 增加 alwaysUseSubUserClass 方法说明

md/android_statistics.md
=> add analytics app channel code setting doc

views/leanengine_guide-node.md, views/leanengine_guide-python.md
另外 Python SDK 也尽快加上这个功能吧，应该不是很复杂，添加之后来文档上加上示例。 @aisk
=> 补充有关 beforeUpdate Hook 的说明

views/realtime_guide-ios.md
=> Fix document error about message query

custom/js/download.js, templates/pages/sdk_down.html
=> 支持动态库和静态库下载

views/realtime_guide-ios.md
我看文档似乎漏改了一个地方？这个修改：https://github.com/leancloud/docs/commit/2ce8c8844f72dafbf5c6883c48f1f06179c680c8
@tang3w @myleslee
=> ios 历史消息查询有个地方描述有些错误

package.json, views/leanengine_guide-node.md
=> LeanEngine: HttpsRedirect 中间件增加 trust proxy 设置

md/ios_crashreporting_guide.md
修复 leancloud-gem 的安装命令。 @myleslee
=> Update leancloud gem installation command

views/realtime_guide-ios.md
增加获取未读消息的示例代码（来源：https://ticket.leancloud.cn/tickets/8937）
=> fix(docs): add code example for processing unread message

package.json
=> fix(doc) fix deps url

md/rest_api.md
=> fix(docs): remove html comment markups that couldn't be rendered correctly

md/realtime_v2.md
=> fix(docs): 增加聊天 hook「_messageReceived」说明

md/android_push_guide.md, md/ios_push_guide.md, md/js_push.md, md/rest_api.md
每个 channel 名称只能包含 26 个英文字母和数字。Closes #796
=> fix(docs): 补充推送频道 channel 名称的限制

views/leanengine_guide-cloudcode.md, views/leanengine_guide-node.md
=> fix(docs): 修复云引擎 cookie-session 中间件的失效链接

views/sms_guide-ios.md, views/sms_guide-js.md, views/sms_guide.tmpl
=> fix(docs): 补充短信模板的系统预留变量的说明

md/ios_os_x_guide.md, views/realtime_guide-ios.md
修复关于 AVObject 子类注册的位置。 @myleslee
=> Fix AVObject subclass registration place

md/ios_push_guide.md, md/push_guide.md
=> fix(docs): 增加使用开发证书推送的设备数量限制的提示

views/sdk_setup-android.md
=> update library version number

.gitignore
for the purpose of local testing, no need to sync.
=> (chore): let Git ignore test.md

md/push_guide.md, views/sdk_setup-android.md, views/sdk_setup-ios.md
=> fix(docs): 修订推送自定义属性的说明

views/realtime_guide-android.md
=> fix(dosc): [Android IM] 将 client.getConversationQuery() 替换为 client.getQuery()

md/rest_api.md
=> fix(docs): 增加美国节点 API 域名及相关说明

md/rest_api.md, views/realtime_guide-ios.md
=> fix(docs): 修订 REST API 中 X-LC-Sign 的说明

md/cql_guide.md, md/error_code.md, md/rest_api.md
=> CQL 增加 insert,update/delete 说明， REST API 增加位运算符

md/push_guide.md
=> 增加定时推送任务查询和取消

views/realtime_guide-android.md
=> fix(docs): 补充 Android 聊天 - isTransient 和 isUnique 同时为 true 时，isUnique 不会生效

md/ios_os_x_guide.md
添加 iOS SDK 中 RPC 云引擎调用的文档。 @leancloud/objective-c @leancloud/docs-editor
=> Add documentation of RPC function call

views/realtime_guide-ios.md
更新 client open 接口的文档。 @leancloud/docs-editor @leancloud/objective-c
=> Update documentation of client open API

views/sdk_setup-android.md
=> add protobuf

md/leancache_guide.md
=> LeanCache: 增加 redisClient on error 事件处理的文档

md/cql_guide.md, md/oauth2_provider.md, md/push_guide.md, md/rest_api.md
=> fix(docs): 修正 Push 概览 UTC 时间格式错误

views/realtime_guide-dotnet.md, views/realtime_guide-ios.md
=> fix(IM-iOS): 增加聊天记录缓存的说明

views/sdk_setup-ios.md
补充 iOS SDK 集成步骤，特别描述了在 Swift 项目中导入模块的步骤。
@leancloud/docs-editor @leancloud/objective-c @hjiang
=> Fix iOS SDK integration steps

md/js_guide.md
=> fix(js): AV.Promise.all 实例代码错误

md/js_guide.md
=> Add js sessionToken section.

archive/ios_realtime_v2.md, custom/js/app.js, md/quick-start-guide.md, md/storage_overview.md, md/tool_tips.md, templates/include/header.html, templates/pages/index.html, views/leanstorage_guide-ios.md, views/realtime_guide-ios.md, views/sms_guide-ios.md
=> 所有 iOS  数据存储文档的链接都指向新的存储文档。

md/ios_push_guide.md
添加处理 device token 的方法的文档。 @leancloud/docs-editor @leancloud/objective-c
=> Add documentation for handling device token

md/android_push_guide.md, md/python_guide.md
Closes #956
@daweibayu @BinaryHB 请审核
=> fix(docs): Android 推送增加 Push 打开统计说明（PUSH_INTENT_KEY）

md/python_guide.md
=> fix(docs): Python 增加 destroy_all() 方法

views/sms_guide-js.md
=> fix(docs): 修复 JS 短信-使用模板 的示例代码错误

md/ios_os_x_guide.md
=> fix(docs): [iOS 存储] 修改 SaveOption.query 描述

md/android_guide.md
leancloud/paas#812
leancloud/android-sdk#514
=> add delete option

views/leanengine_guide.tmpl
=> feat(LeanEngine): 增加 `LEANCLOUD_REGION` 环境变量的说明；环境变量前缀修改

md/sns.md, md/start/ios_start.md, views/sdk_setup-ios.md
将通过 CocoaPods 集成动态库的文档移除，因为 CocoaPods 处理动态库还有些问题。手动集成是 OK 的。
@leancloud/docs-editor @leancloud/objective-c
=> Remove documentation about iOS dynamic framework

templates/include/header.html, templates/pages/index.html, views/leanstorage_guide-ios.md
=> fix(docs): [云引擎] 恢复旧导航菜单

views/sdk_setup-ios.md
=> fix(docs): [iOS Setup] 更新使用美国节点的代码

views/sdk_setup-android.md, views/sdk_setup.tmpl
@daweibayu @wujun4code @myleslee
=> add issue list for android setup

md/leaninsight_guide.md
=> fix(docs): [离线分析] 说明 _Conversation 和 _User 表中不支持查询的字段

views/leanstorage_guide-ios.md, views/leanstorage_guide.tmpl
=> ref issues: #1020 #996 #977

md/leaninsight_guide.md
=> fix(docs): [离线分析] 删除示例代码中的多余括号 (err))

md/quick-start-guide.md
=> fix(docs): [常见问题] 更新数据导入导出链接

md/dashboard_guide.md, views/leanengine_cloudfunction_guide.tmpl
=> fix(docs): [控制台] 数据导入不触发云引擎 hook 函数

md/js_guide.md
=> 修复 tabs 样式对老文档的错误渲染。

views/leanstorage_guide-ios.md
=> fix(docs): [存储 iOS] 示例代码错误 setObject:forKey: 颠倒了

views/leanengine_guide.tmpl
=> fix(docs):[备案] 明确域名绑定的DNS记录和备案完成后的后续操作

views/leanengine_cloudfunction_guide.tmpl
Closes #982
@wujun4code @sdjcw
=> fix(docs): [云引擎] 补充 RPC 调用云函数方法（iOS 和 Android SDK）

md/ios_push_guide.md
=> fix(docs): [推送] iOS: AVOSCloudIM => AVOSCloud

views/leanengine_cloudfunction_guide-node.md, views/leanengine_cloudfunction_guide.tmpl
使用 Tab Block 功能将 SDK 调用云函数的文档合并。
=> 使用 Tab Block 功能将 SDK 调用云函数的文档合并。

.gitignore, md/js_realtime.md, md/realtime_guide-js.md, md/realtime_v2.md, templates/include/header.html, templates/pages/index.html, views/realtime_guide-js.md.bak
https://leancloud-docs-pr-1127.herokuapp.com/realtime_guide-js.html
由于差异太多太杂，最终没有使用模板生成工具，复制了一份 Android 的文档进行修改。
前半部分的示例都配了能直接运行的 Demo（右上角有个运行按钮），后半部分没有写了，上线之后再补。
@myleslee @wujun4code 
cc @nicecui @BinaryHB @jwfing
=> Add document for JavaScript Realtime SDK v3

views/leanengine_cloudfunction_guide.tmpl, views/sdk_setup-android.md
=> fix(docs): [安装 Android] 第三方登录，补充新浪微博 SDK 的集成方式

views/realtime_guide-ios.md
修复查询对话时的一处文档错误。 @leancloud/docs-editor
=> Use contain all members constraint to query conversation

md/dashboard_guide.md
=> (feat) 补充 JSON 批量导入 class 说明

md/faq.md
=> fix(docs): [FAQ] 补充 query.count 算一次 API 调用

md/leancache_guide.md, md/leanengine_cli.md
* avoscloud 更名 lean
* 简化 Node.js 环境的安装说明，细化关于权限的说明
* 更新执行 lean 命令后的输出
* 补充「体验版无预备环境」这一设定
=> [云引擎命令行工具使用详解] 大量细节修改

custom/js/md.js
=> feat: 将各文档的标题放入 <title>

md/realtime_v2.md
=> 补充实时通信服务 4101 & 4102 错误码

md/status_system.md
=> (fix) Remove order in /subscribe/statuses

views/leanstorage_guide-js.md, views/sdk_setup-js.md
=> typescript 补充

md/realtime_rest_api.md
=> 补充参数表格，有些用户容易忽略上下文。

views/acl_guide-python.md, views/acl_quick_start-python.md, views/leanstorage_guide-python.md, views/relation_guide-python.md, views/sdk_setup-python.md
1, 根据reviewer的意见修改了PR，之前的PR有点混乱，关掉了，重新开一个。
2, 之前的地址在: https://github.com/leancloud/docs/pull/1190
=> Add python-sdk example code, including: ACL, leanstorage, set-up.

views/leanstorage_guide.tmpl
=> fix the link_to_acl bug in templete

views/acl_guide-python.md
=> fix mis-typing in acl_guide-python.md

md/faq.md, md/tool_tips.md, templates/include/doc-nav.html, templates/pages/index.html
=> Qcloud fix

custom/less/section-docs.less
style conflicting with in-page links
=> fix(style):  fix the border issue with code language toggles

views/leanstorage_guide-python.md
增加两个block
1，code_fetch_todo_by_objectId
2，code_update_todo_content_with_objectId
=> add two missing block in python-storage docs

md/faq.md, templates/pages/faq_list.html
=> fix(docs): [FAQ] iOS 项目打包后的大小

views/leanstorage_guide-android.md, views/leanstorage_guide-python.md
去掉结尾的 `$`
会得到错误匹配：https://github.com/leancloud/docs/pull/1268/files#r68481799
=> fix(docs): [存储] 修复「不包含」正则表达式

views/leanstorage_guide-php.md, views/sdk_setup-php.md
这里需要确认一下模版里有 masterKey 这个变量吗？
@myleslee @wujun4code PTAL
=> PHP: 存储补充 sdk 安装指南

custom/js/md.js, views/leanengine_cloudfunction_guide-node.md, views/leanengine_cloudfunction_guide-php.md, views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide-php.md, views/leanengine_webhosting_guide.tmpl
与 nodejs 主要的不同在于［云函数超时］这里，PHP 暂时不支持异步调用，没有给出 ［超时处理方案］。
@sdjcw @myleslee 求审阅。
=> PHP: 云引擎文档

templates/include/header.html, templates/pages/index.html
=> 添加 php 文档链接，正式发布上线。

md/rest_sms_api.md, views/leanstorage_guide-android.md, views/leanstorage_guide-ios.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-python.md, views/leanstorage_guide.tmpl
Fixes #1300
Fixes #1297
Fixes #1295
Fixes #1303
=> fix(docs): 修改错字、格式和模板

md/app_search_guide.md
=> (fix) 修正 moreLikeThis url 错误

md/realtime_guide-js.md, md/webrtc-js.md
=> feat: 增加 JS WebRTC 插件文档

md/faq.md, templates/pages/faq_list.html
=> fix(docs): [FAQ] 增加「先验证手机号码再注册」

md/leanengine_examples.md
=> fix(docs): [云引擎] 增加 IM 签名的 Demo

views/leanengine_webhosting_guide-node.md, views/leanengine_webhosting_guide.tmpl
=> fix(docs): [云引擎] Node.js 补充环境变量调用方式

md/ios_push_guide.md, md/realtime_v2.md
@leancloud/docs-editor little typo
=> fix typo for realtime_v2

md/android_push_guide.md
=> change to AppSecret

custom/js/download.js, custom/less/section-docs.less, templates/pages/sdk_down.html
=> 重写 下载页面，增加开源下载支持

views/leanengine_webhosting_guide-node.md
=> [Node SDK] 补充有关 koa 框架的内容

md/realtime_guide-js.md
=> feat(realtime-js): 增加对话「查询选项」部分

views/realtime_rest_api.md
=> (doc) 增加两个 API 文档

views/push_guide.md
将 silent 参数从 top level 改为 android 特有的一个参数。
=> 修改 Android silent push 说明

views/sdk_setup-ios.md, views/start/ios_start.md
更新了 Objective-C SDK 的快速入门，并覆盖安装指南。 @leancloud/docs-editor
=> Update objc-sdk installation doc

views/leanengine_cloudfunction_guide-php.md, views/leanengine_webhosting_guide-php.md, views/leanstorage_guide-php.md, views/sdk_setup-php.md
参考 #1327 
为了各语言的一致性，PHP 去掉 `LeanObject` 中的 `Lean` 前缀。
@myleslee @wujun4code @tang3w @sdjcw
=> PHP 去掉类名 Lean 前缀

views/android_push_guide.md
=> update huawei push manifest

views/error_code.md
规避用户在客户端用 master key 来改 _User 的想法。
=> update error code 206 explanation

views/realtime_guide-js.md, views/webrtc-js.md
- Add API documents' links
- refactor SDK installation section
- other chores
=> chore: refine js-realtime documents

views/leanstorage_guide-android.md
新增 AVQuery.doCloudQueryInBackground() 方法的第三个参数说明，避免用户传子类时不知道为什么报错 ClassCastException。
=> update android cloud query code about subclass

views/leanstorage_guide-js.md
增加 createWithoutData 方法后需要的 fetch 代码
=> update js storage code

views/realtime_guide-js.md
=> fix(js-realtinme): use plural form with members related events

views/leanengine_webhosting_guide-java.md
=> fix(LeanEngine): 代码段中的应用变量未被渲染

views/leanengine_webhosting_guide-node.md, views/leanengine_webhosting_guide.tmpl
=> [云引擎 Node] 补充打开请求日志的方法

views/leanengine_faq.md, views/leanstorage_guide-js.md
=> 更新 JS SDK 堆栈溢出的解决方案

views/faq.md, views/leancache_guide.md
=> fix(docs): [LeanCache] 增加本地调试的说明

views/leanstorage_guide.tmpl
=> fix(docs): [存储] 补充说明密码修改后 sessionToken 可能需要更新

templates/layouts/download_clean.swig, templates/pages/index.html, templates/pages/index_old.html
调整了一下 index 页面的内容组织方式，以求文档脉络更清晰一些，方便新用户上来能快速找到自己需要的内容。
预览可以看这里：http://newdoc.leanapp.cn/
=> re-org index.html

views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl, views/sdk_setup-swift.md
更新 Swift SDK 的所有代码块。一方面适应了新的 API；另一方面改进了一些逻辑，引入推荐的写法。 
@leancloud/docs-editor
=> Update Swift code blocks

views/leanengine_cloudfunction_guide-java.md
=> fix(docs): wrong link for java sdk

views/leanengine_cloudfunction_guide-java.md, views/leanengine_cloudfunction_guide.tmpl
=> fix(docs): [云引擎] 云函数-修订聊天 Hook 用法说明

views/leanengine_cloudfunction_guide-php.md
=> PHP 添加实时通信 hook

views/push_guide.md
=> 推送增加对 ios 10 新增参数使用描述

templates/include/doc-nav.html, templates/pages/index.html
=> fix(docs): [nav] 增加应用内社交和应用内搜索的 REST API 链接

views/chatkit-android.md, views/livekit-android.md, views/sdk_setup-android.md
=> fix(docs): 更新 Android 的 maven 仓库地址

views/chatkit-ios.md
=> fix(docs): [ChatKit] iOS 补充 #import <ChatKit/LCChatKit.h>

views/status_system.md
* 增加删除收件箱消息 REST API 说明
* API 域名替换成 api.leancloud.cn
@myleslee @wujun4code
=> (feat) 增加删除收件箱消息说明

custom/js/md.js
change titles from「LeanCloud 文档 - Android 数据存储开发指南」to「Android 数据存储开发指南 - LeanCloud 文档」
=> fix: reverse title

views/ios_push_guide.md
iOS10 推送适配@leancloud/ios-group  @leancloud/tech-support  @leancloud/push
=> Update ios_push_guide.md for iOS10

templates/pages/index.html
=> fix: broken python guide link

views/acl_guide-js.md
=> fix(docs): [ACL] JS 变量 administratorRole 未提前声明

templates/include/doc-nav.html, templates/pages/index.html, views/leanstorage-started.tmpl
=> add leanstorage-getting-started into doc nav

templates/include/doc-nav.html
=> fix(nav): add a link to PHP Setup doc

views/sdk_setup-android.md
=> fix(setup): [Android] 强调实时通信也需要 PushService

views/app_search_guide.md, views/rest_api.md, views/status_system.md
* resetUnreadCount
* refreshSessionToken
=> 补充新 API 说明

templates/include/doc-nav.html, templates/pages/index.html
https://leanticket.cn/t/leancloud/3078
=> 替换导航中的 JS 推送文档链接，指向存储中文档中的推送部分

views/realtime_guide-js.md, views/weapp.md
=> 小程序文档增加文件与实时通讯用法

views/leanstorage_guide.tmpl
=> fix(docs): [存储] 未经验证的手机号码也可以登录

views/leanstorage_guide.tmpl
=> fix(docs): [存储] _File 中的记录内容不能修改

views/leanstorage_guide-js.md, views/leanstorage_guide.tmpl
=> fix(docs): [SNS] JS 补充 openid 和 uid 的区别

images/apns-registration.svg, images/push-workflow-android.svg, images/push-workflow-ios.svg, views/ios_push_guide.md
- svg: use system font for rendering
- svg: unified canvas size: 640x360
- svg: add text wrapping
=> chore: refresh svg figures & fix heading level problem in ios push doc

views/leanstorage_guide-js.md
Closes #1411
Swift
部分要不要改在等确认：https://leancloud.cn/docs/leanstorage_guide-swift.html#排序
=> fix(docs): [存储] JS 多字段排序要用 addAscending(key) 而不是 ascending(key)

custom/js/demo.js, views/feedback.md, views/realtime_guide-objc.md, views/realtime_v2.md, views/sns.md
1、对 demos 页面进行更新；
2、删掉有关 LeanChat-iOS 的文档说明。
=> Change demos.html and delete LeanChat-iOS docs

views/push_guide.md
=> 增加给某个设备类型设备的推送说明

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-python.md, views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl
=> fix(docs): [存储] 更改保存选项 query 示例：多请求更新账户余额，不能出现负值

views/android_push_guide.md
=> fix(docs): 修改措词「混合推送注册成功后才会产生 vendor 字段」

views/android_push_guide.md, views/leanstorage_guide.tmpl, views/realtime_rest_api.md, views/rest_api.md
Closes #1677
Closes #1708
Closes #1710
=> fix(docs): [REST] 在数组查询中增加 $in 用法

views/weapp.md
=> chore(weapp): revert 初始化位置的改动

templates/include/_op.html, views/cql_guide.md, views/rest_api.md
=> feat: [CQL] 增加内置函数 op() 汇总清单

views/realtime_guide-objc.md
=> Revert "update objc realtime API `markAsReadInBackground`"

views/realtime_rest_api.md
=> 更新聊天记录增加强调

views/ios_push_guide.md
=> fix(docs): iOS 推送增加 Data 内容的说明

images/todo-schema.svg, views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-php.md, views/leanstorage_guide-python.md, views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl
=> feat: [存储] 增加 Todo 的 schema 说明

views/_parts.html, views/sdk_setup-js.md, views/start/js_start.md
=> fix(docs): [安装] JS 更新 SDK 版本

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-php.md, views/leanstorage_guide-python.md, views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl
=> fix(docs): 存储查询内容调整，区分数组 [not]ContainedIn 和字符串 contains 用法

views/leaninsight_guide.md
Closes #1759
换行中有非法字符导致 Markdown 无法被正确渲染
=> fix(docs): [Insight] 代码块格式未正确渲染

templates/pages/faq_list.html, views/faq.md, views/leanengine_guide-cloudcode.md, views/leanengine_upgrade_3.md, views/realtime_guide-js.md
=> fix(docs): AV.initialize => AV.init

views/leanstorage_guide-js.md
=> fix(docs): 修改 JS Promise 示例

views/android_push_guide.md
=> add mixpush faq

templates/pages/weapp-domains.html
only five domains are allowed now.
=> update weapp socket doamin whitelist

views/start/php_start.md
=> 更新 php 快速入门文档

custom/less/section-docs.less, views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-php.md, views/leanstorage_guide-python.md, views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl, views/test.md, views/test.tmpl
修复「使用关联表实现多对多关系」链接错误
恢复 callout 中的链接的颜色
=> fix: [存储] 获取对象描述错误 ObjectId > AVObject

views/leanstorage_guide-js.md
=> fix: [存储] JS  修正  CQL 的 count 示例代码

views/push_guide.md
=> fix(docs): [推送] deviceProfile 的值不能是 _default

views/dashboard_guide.md, views/dashboard_guide_tab.md
=> fix: [dashboard] 用于数据导入的文件每个不能超过 30 MB

views/sns.md
=> fix: [SNS] iOS 不支持微信 SSO

views/realtime_rest_api.md
=> 暂时隐藏系统广播查询文档

views/realtime_rest_api.md
=> Revert "暂时隐藏系统广播查询文档"

Gruntfile.js, custom/js/md.js, custom/less/section-docs.less, package.json, templates/layouts/download_clean.swig, templates/layouts/template.swig
将修改 Title 和设置首页内容分类导航的任务从 jQuery 中分割出来
=> feat: 增加文档修改日期

views/leanstorage_guide-js.md
2.0 只去掉了回调参数，save 的第一个参数还是 attrs
3.0 的时候考虑去掉
=> 去掉 JS SDK save options 的说明

views/leanstorage_guide-js.md, views/leanstorage_guide.tmpl
其他语言版没有错误，都用的是 Tag
Closes #1821
=> fix: [存储] JS - AV.Relation 示例代码错误 Todo => Tag

views/webhosting_weixin.md
=> fix: [云引擎] 微信公众号修复 package.json 的语法和内容

views/leanengine_cloudfunction_guide-python.md
close: https://github.com/leancloud/python-sdk/issues/243
=> feat: add custon python cloud function name description

views/leanengine_cloudfunction_guide-python.md
close: https://github.com/leancloud/python-sdk/issues/242
=> feat: add python leanengine current object description

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md
Verfiy 拼写错误，新版 Android/Java SDK 会废弃这一接口。
=> fix: [Java] requestEmailVerify > requestEmailVerfiy

views/unity_guide.md
=> chore: [Unity] 示例代码格式混乱

views/_data.njk, views/leanstorage_guide.tmpl, views/rest_api.md
=> fix: [REST] 增加 Class 命名规范

custom/less/section-docs.less, templates/pages/sdk_down.html
=> fix: layout issue - SDK items don't wrap in Safari

views/sdk_setup-js.md
update CDN
use taobao registry
remove typings
remove bower
=> update js setup guide

views/rest_api.md
=> fix: [REST] batch 返回码 200 并不代表其中包含的所有操作都成功执行

views/leanengine-node-sdk-upgrade-1.md
=> LeanEngine: node sdk 升级文档增加一些细节描述

views/realtime_guide-android.md, views/realtime_guide-js.md, views/realtime_guide-objc.md, views/realtime_guide.tmpl
=> chore: combine sample code of different languages

templates/pages/sdk_down.html, views/leanengine_cli.md
=> fix: update SDK download links to be China-friendly

custom/js/demo.js, custom/js/weapp-domains.js, templates/pages/weapp-domains.html, views/sdk_setup-js.md, views/weapp.md
- 小程序增加了 FAQ
- 小程序域名配置去掉了全局的 loading
- 移除了 LeanMessageDemo 的 iOS 与 Android 链接（已废弃），增加 Web 版本链接
=> chore: js 相关文档更新

views/sns.md
=> fix: SNS Android 补充 QQ 的 Scheme 属性

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md
=> fix: [Android/Java] API typos: requestEmailVerfiy > requestEmailVerify

views/leanstorage_guide-java.md, views/leanstorage_guide-objc.md
修改 fetch 对象的示例代码，以符合文档的描述。
@leancloud/android-group @leancloud/docs-editor
=> Update code example for fetching object

Gruntfile.js, custom/js/app.js, views/rest_api.md
=> fix: update X-LC-Key to X-LC-Sign in demo code

views/leanengine_cli.md, views/leanengine_quickstart.md, views/weapp.md
=> fix: lean checkout > lean switch

Rakefile, views/leanengine_faq.md
麻烦 @ym 看下措辞是否合适，并且将该页面链接增加到错误响应页面。
=> LeanEngine: 增加 ip 连接数限制的说明

views/realtime-unity.md
=> feat: unity realtime docs.

custom/js/demo.js
脚本里不支持使用 HTML tag。:(
Closes #1963
=> feat: add Flask Todo Demo

views/realtime_guide-android.md
=> fix: [IM] Android 自定义消息不可遗漏空的构造方法和 Creator

Gruntfile.js, fabfile.py, package.json
* 增加评论系统用户登录，因为评论系统将改为只有特定用户才能写入文档等信息。
* Doc version 属性使用更佳合理的生成方式。
=> fix(comment): 评论插件一些修改

views/realtime_guide-js.md
changelog: https://github.com/leancloud/js-realtime-sdk/releases/tag/v3.4.0
=> JS 实时通讯 v3.4 更新

views/sdk_setup-android.md
删除 httpmime，java WebSocket 也已经升级到了 1.3.2。
=> delete unused jar

views/leanengine_cloudfunction_guide-node.md
=> 🔨 [云函数开发指南 · Node.js] 更新至 Node SDK 2.0

deploy.sh
=> New deploy method

custom/js/weapp-domains.js, templates/pages/weapp-domains.html
假设了使用小程序的没有很老的应用，因此只判断了应用的后缀。严谨的判断成本太高了。
=> 为小程序增加 app router 2 中新增的域名

views/realtime_guide-objc.md
修复发送音频消息的示例代码中错误的消息类型。 @leancloud/docs-editor
=> Fix wrong type for audio message

views/realtime_guide-objc.md
=> Add doc for message read and receipt

views/leanengine_cloudfunction_guide-java.md
=> 修复一下 Java 版的 reciever offline hook 代码

views/error_code.md
=> fix: check app settings for error 403

views/error_code.md
=> fix: 补充 605 SMS sign not verified 说明

views/realtime_guide-objc.md
更新文档，使用 `conversation:didUpdateForKey:` 来观察对话属性的变化。 @leancloud/docs-editor
=> Update doc for observing last message timestamp and unread messages count

views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide-node.md
=> fix: 使用 AuthOptions 的 useMasterKey 来启用或关闭超级权限

views/leanengine_webhosting_guide-node.md
=> fix: 网站托管的自定义路由超时设置

views/realtime-unity.md
=> fix: ios websocket lib build errors.

views/sms-guide.md
为 objc sdk 增加短信图形验证码的示例代码。 @leancloud/sdk-only @leancloud/docs-editor
=> Add code snippets about short message captcha for objc-sdk

views/sms-guide.md
更新请求短信的代码片段：1) 用新接口代替废弃的接口；2) 增加图形验证码的相关字段。
@wujun4code @myleslee
=> Update code snippets for short message request

views/realtime_v2.md
Closes #2044
To be merged after #2040 as necessary changes have been made there:
https://github.com/leancloud/docs/pull/2040/files#diff-9b193ffc9d5714cac
0d9670e39a87615R5
=> fix: IM 概览中加入对话的有效期

views/leanengine_cloudfunction_guide.tmpl
=> fix: 云引擎定时器 24 小时内超时 30 次以上会被禁用

views/livequery-guide.md
=> Add code for importing live query header

views/livequery-guide.md
=> fix: LiveQuery 去掉单点登录

.gitignore, Gruntfile.js, templates/include/doc-nav.html, templates/layouts/kb.swig, templates/pages/index.html, views/kb-network-connectivity-diagnosis.md
=> feat: 网络连通性诊断流程

custom/js/md.js, views/sdk_setup-js.md
=> fix: [Setup] add initialization code for Node.js

custom/js/demo.js, templates/pages/demo.html
=> fix: [Demo] remove platforms that have no demos

views/_im.njk, views/realtime_guide-js.md, views/realtime_guide.tmpl, views/realtime_v2.md
=> fix: [IM] 服务端消息最多存放 6 个月

views/app_search_guide.md
=> (feat) 增加应用内搜索自定义词库说明

views/sdk_setup-php.md
=> fix: [Setup] PHP: wrong region code for China node

Gruntfile.js, comment.js, package.json, test/comment-example.html, test/comment-test.js, test/mocha.opts
使用 REST API 而不是 JS SDK 实现，提高灵活性。
=> fix: 文档评论插件更新

views/leanstorage_guide-android.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide.tmpl
=> feat: [Storage] Authentication via SessionToken

views/ios_push_guide.md
避免在重置应用 badge number 的同时取消本地通知。
=> Do not cancel local notification when reset badge

views/leanengine_cli.md
close: https://github.com/leancloud/lean-cli/issues/299
暂时先不要合并，等待 API 端关于日志导出的接口重新上线。
=> feat: add log export and group switch related description

templates/pages/opencourse.html
基于 LeanCloud 快速搭建聊天机器人
使用 LeanMessage 开发 H5 互动游戏
=> feat: add new courses

views/leancache_guide.md
=> feat: 新增 Java SDK 如何连接 LeanCache

views/_data.njk, views/rest_api.md
=> fix: [REST] 去掉与 Relation 相关的文档，增加弃用说明

views/leanstorage_guide-android.md, views/leanstorage_guide.tmpl
=> feat: [存储] Android 增加错误说明: already has one request sending

views/leanstorage_guide-js.md
=> feat: [存储] JS 使用 toJSON() 获取 AV.Object 的全部属性

views/leanengine_webhosting_guide-python.md, views/sdk_setup-python.md
Python SDK 2.0 改了个包名，这个 PR 主要修改之前文档中关于包名的地方，以及升级指南。
=> Python sdk

views/android_push_guide.md
=> feat: [推送] Android 设置应用间推送唤醒

views/leanengine_webhosting_guide-java.md, views/leanengine_webhosting_guide-php.md
=> chore: [云引擎] Java & PHP 增加对环境变量的注释

views/livequery-guide.md
https://leanticket.cn/tickets/13786#59a53e71128fe1005af37af0
=> fix: script tag is not self-closing

views/realtime_guide-js.md
=> 修改 push data 文档

views/leanengine_cli.md
介绍 lean-cli 的 `metric`。
但渲染出来的表格，宽度有点别扭，如何调整各栏的宽度？
=> Introduce metric command in lean-cli.

Gruntfile.js, custom/js/app.js, custom/js/weapp-domains.js, views/weapp.md
=> feat: REST API 域名升级到独立域名

views/realtime_guide-android.md, views/realtime_guide-js.md, views/realtime_guide-objc.md
Closes #2290
fixes errors in #2290
=> chore: [IM] update demo code

views/realtime_v2.md
=> fix: missing realtime manage guide

views/leanengine_cloudfunction_guide-node.md
https://github.com/leancloud/cloud-code/pull/1294
=> [云函数开发指南 · Node.js] 在线编辑支持切换 SDK 版本

views/chatkit-android.md
=> feat: [ChatKit] Android - 如何更新用户相关的本地缓存

views/rest_api.md
=> feat: rest api upload file not available at us node.

views/analytics-guide.md
=> feat: analytic data format.

templates/pages/sdk_down.html
Closes https://github.com/leancloud/avfr/issues/1257
=> feat: 更新下载页面，Android SDK 已开源

views/rest_api.md
=> feat: [REST] 补充更多的用户反馈接口

views/leanstorage_guide.tmpl
=> enhance: avuser  single sign on.

views/app_search_guide.md
=> fix: [应用内搜索] avoscloud > leancloud

views/leanstorage_guide.tmpl
=> chore: [Storage] remove scenarios for files from Swift doc

custom/less/section-docs.less, custom/less/theme-core.less, templates/pages/weapp-domains.html
=> chore: [weapp-domains] UI update

views/leanstorage_guide-swift.md
添加 include pointer 的示例代码。 @myleslee
=> Add code snippet about including pointer data when fetch object

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-swift.md, views/leanstorage_guide.tmpl
=> fix: [Storage] missing example code for Pointer & File

views/leanstorage_guide.tmpl
=> fix: [storage] saveOption query doesn't work on new object

views/realtime_guide-android.md, views/realtime_guide-objc.md, views/realtime_v2.md
=> chore: remove unrelated LeanMessage links for iOS & Android

views/weapp.md
=> feat: 使用 unionId 登录微信小程序

views/_data.njk, views/rest_api.md, views/test.tmpl
让参数列表支持排序
lost_user_7：7 天流失用户数
page_exit：页面退出
Closes #2390
=> feat: [统计] 增加 metrics: lost_user_7、page_exit

templates/pages/weapp-domains.html
fix https://leanticket.cn/tickets/14635
=> fix: upgrade SDK version for weapp domains page

views/sns.md
=> fix: [SNS] Android revamp

views/rest_sms_api.md, views/sms-guide.md
=> chore: [SMS] US SMS ready

custom/js/md.js, views/leanengine_cloudfunction_guide-node.md, views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide-node.md, views/sms-guide.md
=> chore: platform over language: Java > Android, Javascript > Node.js

views/rest_api.md
=> fix: [REST] 移除与实时统计相关内容

views/_data.njk
=> fix: [REST] remove metrics that are no longer available

views/rest_api.md
=> feat: [REST] 统计数据收集补充必填字段 ts

views/leanengine_cli.md
=> fix: [CLI] 注明登录各节点的参数值

views/_data.njk
=> fix: accordion panel should escape hashing machnism

Gruntfile.js
keep it in line with TOC anchor algorism
=> fix: correct hashing algorism for repeated headings

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-php.md
=> fix: [存储] 补充 Android 验证 SessionToken 的示例代码

templates/pages/sdk_down.html, views/_data.njk, views/sdk_setup-android.md
Closes #2442 Android 手动安装 jar 包方式更新
=> fix: jar files no longer available for Android SDK

views/realtime_v2.md
两处修改：
1. RTM 创建对话 REST API 增加 unique 参数
2. 增加黑名单签名逻辑
=> rtm api add unique param

custom/js/weapp-domains.js, templates/pages/weapp-domains.html
以及修复了切换应用文件下载域名没有更新（提示 SDK 已经初始化）的问题。
https://github.com/leancloud/paas/issues/988
=> fix(weapp): e1 更新域名白名单

views/push_guide.md
=> fix: 在 Web 上接收推送消息已弃用

views/weapp.md
增加一个「微信小程序」真机运行时的常见问题。
社区问题链接：
https://forum.leancloud.cn/t/topic/17279/
https://forum.leancloud.cn/t/topic/17121
=> feat: FAQ 小程序真机不能正确保存类名

views/realtime_guide-objc.md
=> fix: 更新设置和读取对话自定义属性的代码

Gruntfile.js, custom/js/app.js
https://github.com/leancloud/paas/issues/988
=> fix: 更新 Rest API 中使用的 e1 域名

views/sdk_setup-php.md
依赖 leancloud/php-sdk#169 的发布，计划发布版本 0.7.0 。
=> PHP 增加 setServerUrl 接口文档

views/realtime_guide-objc.md
=> Update Message modifying & recalling

views/_parts.html, views/livequery-guide.md
=> feat: 补充 JS SDK 的 LiveQuery Debug 代码

views/_rtm_rest_api_v2_system.njk, views/realtime_rest_api_v2.md
烦请只是 Review 暂时先不合并，由我来合并。因为需要等待 API 发布。谢谢！
关联：https://github.com/leancloud/uluru-platform/pull/4376
=> 增加服务号各种修改撤回消息说明

views/_parts.html, views/sdk_setup-js.md, views/sdk_setup.tmpl
=> feat: new JS SDK Setup doc

templates/include/doc-nav.html, templates/pages/index.html, views/weapp.md
- 将 SDK 安装部分指向新的安装指南
- 更新了 unionId 是的使用说明
需要等 #2490 完成。
=> feat: 补充微信小游戏相关的内容

views/_rtm_rest_api_v2_client.njk
=> add v2 unread

views/realtime_v2.md
=> refact offline msgs

views/error_code.md
=> feat: error code 608

views/leanengine-rest-api.md
=> remove sensitive content

views/realtime_guide-android.md, views/realtime_guide-js.md, views/realtime_guide-objc.md, views/realtime_guide.tmpl
=> 根据消息类型查询聊天记录文档补充

views/_leanengine.njk, views/leanengine_cloudfunction_guide.tmpl, views/leanengine_guide.tmpl
=> update number of timers

custom/js/weapp-domains.js, templates/pages/weapp-domains.html
=> 小程序域名页提示绑定文件域名

views/sdk_setup-objc.md
=> NSError 格式更新

views/sdk_setup-js.md
preview: https://leancloud-docs-pr-2613.herokuapp.com/sdk_setup-js.html#hash-42090259
=> JS SDK 安装指南 增加 Laya 部分

views/leanengine_cloudfunction_guide-php.md, views/leanstorage_guide-php.md, views/leanstorage_guide.tmpl, views/sdk_setup-php.md
=> PHP SDK: `Object` 更名 `LeanObject`

views/ios_push_guide.md
iOS SDK 选择开发环境推送证书，文档补充一行示例代码。
=> select push certificate

views/chatkit-android.md, views/chatkit-ios.md
ChatKit 文档增加醒目条幅「对于 ChatKit 的二次开发 LeanCloud 不提供任何技术支持」。
=> add chatkit notice

views/leanengine-rest-api.md, views/leanengine_webhosting_guide.tmpl
=> chore: relocate env-specific text of leanengine

views/_rtm_rest_api_v2_system.njk
遍历查询订阅者：https://leancloud.cn/docs/realtime_rest_api_v2.html#hash-348231988
=>  REST API 遍历查询订阅者需要 Master key。

views/realtime_guide-objc.md
=>  update conversation option

views/leaderboard-rest-api.md
=> (feat) Add leaderboard delete score endpoint

custom/js/weapp-domains.js, templates/pages/weapp-domains.html
- 获取 fileToken 时使用 masterKey
- 移除所有过时的域名
=> feat: 更新小程序域名白名单页

views/acl-guide.md, views/livequery-guide.md, views/relation-guide.md, views/sms-guide.md
为 relation guide 补充了 Swift 示例代码。目前还只是 Objective-C 示例代码的翻译，不是 Swift SDK 的示例代码。
@leancloud/docs-editor
=> Add swift snippets for relation guide.

views/rest_api.md
补充 UnionID 新账户体系 REST API 使用文档。
Fixes #2456
=> UnionID login for REST API

views/play.md
之前 play.html 修改为了 multiplayer.html，但是市场材料册子上还是 play.html，所以临时增加这个页面，等到活动完毕或册子发完之后，再下线这个页面。
=> 为市场部资料临时增加 play.html

views/unity_guide.md
=> Revert "feat: unity switch app."

views/sdk_setup-swift.md
更新了 Swift SDK 的快速入门文档。 @myleslee
=> Update doc for setting up Swift SDK.

views/sms-guide.md
=> fix: code block rendering issue

views/android_mixpush_guide.md
Fix ticket: https://leanticket.cn/tickets/18715
=> change AVMixpushManager to AVMixPushManager

views/client-engine-quick-start-node.md
=> fix: appId & appKey cannot be rendered at all

archive/leanengine_guide-node.md, views/leanengine_guide-cloudcode.md, views/leanengine_webhosting_guide-java.md, views/leanengine_webhosting_guide-node.md
A typo was found during translation to English.
=> Fix typos.

views/realtime_guide-js.md, views/sdk_setup-js.md
=> Remove reference to region init param

views/leanengine_webhosting_guide-java.md
明明已经说了如何在命令行启动 jar 项目 https://leancloud.cn/docs/leanengine_webhosting_guide-java.html#hash-1707077315
=> remove a conflicting statement.

views/weapp.md
=> remove deprecated function signUpOrlogInWithAuthDataAndUnionId

custom/js/demo.js
其实云引擎的 Demo 已经列在这里了 https://leancloud.cn/docs/leanengine_examples.html 我都不知道这里还有一个列表。
=> 👽 Remove broken demo links

views/error_code.md, views/rest_api.md
- update links
- refine synopsis
=> trivial changes on REST API doc

views/pay-beecloud.md, views/realtime_guide-android.md
Also replace all mixed content(http).
=> fix: replace or remove dead images.

private/realtime_guide-js.md, views/dotnet_realtime.md, views/realtime_guide-android.md, views/realtime_guide-js.md, views/realtime_guide.tmpl, views/wp_realtime_v2.md
=> 启用混合推送后的 Android 的离线推送和静音机制

views/storage_overview.md
将《存储服务总览》中的 SDK 列表与已有 SDK 同步，同时改进格式、统一用词。
=> 更新《存储服务总览》中的 SDK 列表

custom/less/section-docs.less
Related conversation:
https://github.com/leancloud/docs-en/pull/44#discussion_r261925441
=> chore(style): docs-en uses default em style

views/leanengine_cli.md
- 修改 `lean -h` 为 `lean help` （前者已废弃）
- 更新了 `lean-cli help` 输出至最新版 0.20.1
=> feat(lean-cli): 补充 lean-cli 命令列表中文说明

views/leanstorage_guide.tmpl
=> feat(js): 存储指南指向微信小程序登录文档

views/realtime-guide-beginner.md
=> feat(rtm): 强调通过 URL 构建的音频消息不自带时长

views/leanstorage_guide-php.md, views/leanstorage_guide-python.md, views/sms-guide.md
=> PHP 和 Python 的短信服务使用指南

views/push_guide.md
=> fix(push): specify apnsTopic manually

views/leanengine_cloudfunction_guide.tmpl, views/storage_overview.md
存储指南总览添加到 hook 函数的链接
resolve #2439
=> feat(hook): 创建、更新、删除对象 hook 流程图

views/sdk_setup-android.md, views/sdk_setup-dotnet.md, views/sdk_setup-java.md, views/sdk_setup-php.md, views/sdk_setup-python.md, views/sdk_setup.tmpl
=> SDK 指南移除节点选择说明

views/android_mixpush_guide.md
相关论坛主题：https://forum.leancloud.cn/t/topic/20005
=> feat(mixpush): 说明如何裁剪 HMS Agent

views/weapp.md
- 增加了 unionid 相关的场景与用法示例
- 数据绑定推荐的用法变更
- 提升存储 SDK 各个服务的标题层级
=> feat: 更新小程序文档登录与数据绑定部分内容

views/leanstorage_guide-js.md, views/sdk_setup-js.md
以及
提升 JS 安装指南中初始化部分的层级（通过降低安装部分的层级）。
=> 增加 JS SDK 序列化反序列化说明

views/leandb_mysql_guide.md
https://github.com/leancloud/cloud-code/issues/1536
=> ✨ LeanDB MySQL guide

views/realtime-guide-intermediate.md, views/realtime_guide-js.md
it accepts an Array<String> instead of a String
=> fix(js): setMentionList usage

views/rest_api.md
=> fix(rest): 补上总览中未列出的推送相关 API

views/livequery-guide.md
=> feat(LiveQuery): no nested query and select

views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-js.md, views/leanstorage_guide-objc.md, views/leanstorage_guide-php.md, views/leanstorage_guide-python.md, views/rest_api.md
related forum discussion: [20241](https://forum.leancloud.cn/t/avquery-get-objectid/20241/)
=> query nonexistent objectid in REST api and SDKs

views/leanengine-rest-api.md, views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide.tmpl
=> fix(LeanEngine): details about X-LC-Prod value

views/realtime-guide-senior.md
=> feat(rtm): block all messages from certain sender

views/leanstorage_guide-python.md
Should open image files in binary mode.
Related forum discussion: https://forum.leancloud.cn/t/python/20247
=> fix(python): error in python sample

views/realtime-guide-intermediate.md
=> cosm(rtm): make extend msg type section switchable

views/rest_sms_api.md
=> fix(sms): cn east region already supports sms

views/_im.md
=> fix: c# rtm sdk is available in unity only

views/acl-guide.md, views/acl_guide_leanengine.md
* refactor: objc & swift part of acl guide
=> Update acl guide

views/rest_api.md
x-lc-prod header can be specified in all rest api calls,
not limited to cloud function calls.
=> feat(rest): describe x-lc-prod

views/acl-guide.md, views/leanstorage_guide-android.md, views/leanstorage_guide-java.md, views/leanstorage_guide-objc.md
=> simplify user query in ACL guide

views/leanengine_cloudfunction_guide-node.md, views/leanengine_webhosting_guide-node.md
Well, not very new.
close #3064
=> Leanengine node sdk new options

views/sdk_setup-php.md
replace phpcomposer.com with aliyun,
as phpcomposer.com is discontinued.
=> fix(php): replace packagist mirror

views/realtime-guide-senior.md
backported from leancloud/doc-en#70
https://github.com/leancloud/docs-en/pull/70/files#diff-950d1297c609f2db1097b1250de659f0R48
=> fix(rtm): wording

views/sdk_setup.tmpl
=> fix(sdk): python init template variable typo

views/_parts.html, views/cql_guide.md
因为 CQL 已经 deprecate，不再进行功能维护，所以在文档中列出一些已知问题及绕过的方法。
=> CQL workarounds

views/im-servermgmt-guide-python.md
=> feat(python): query conversation

views/sdk_setup.tmpl
fix  https://forum.avoscloud.com/t/android-java-sdk/20831
=> fix_sdk_setup_java_ gradle

views/leanengine-rest-api.md, views/leanengine_cloudfunction_guide.tmpl
=> fix(engine): refine rpc call result description

views/im-servermgmt-guide-python.md
=> fix(rtm): python sdk is meant for server side only

views/android_push_guide.md
`setDefaultPushCallback` is not applicable for mixpush.
related ticket: 20928
=> fix(push): no setDefaultPushCallback for mixpush

views/leanengine_faq.md
=> fix(LeanEngine): rpc call unexpected serialization

views/sdk_setup.tmpl
close leancloud/java-unified-sdk#64
=> feat: java-unified-sdk not support old devices

Gruntfile.js
=> fix: host variable

views/android_mixpush_guide.md, views/sdk_setup.tmpl
Fix 工单 [21485](https://leanticket.cn/tickets/21485)。
=> fix-mixpush-version

custom/js/demo.js
下架旧短信 Demo，换成 java_unified_sdk 新的 Demo.
=> change-java-sms-demo-URL

views/android_mixpush_guide.md
=> add-HMS-mixpush-recevier

views/leanstorage_guide.tmpl
Previously there was an option in dashboard
to adjust authData visibility for compatibility issue.
This option is unavailable now.
See also leancloud/uluru-platform#5354
Brought to attention by @shifuchen98
=> fix(login): update authData security control

views/custom-api-domain-guide.md, views/sdk_setup.tmpl
=> feat: update swift sdk init usage

views/leanstorage_guide.tmpl
https://github.com/leancloud/docs/issues/3241
=> feat!(storage_guide): hide current user of swift.

views/custom-api-domain-guide.md
=> fix: domian guide weapp whitelist update

views/_rtm_rest_api_v2_chatroom.njk, views/_rtm_rest_api_v2_normal.njk, views/_rtm_rest_api_v2_system.njk, views/push_guide.md, views/realtime_rest_api_v2.md
关联：https://github.com/leancloud/uluru-platform/issues/5841
=> conversation 表操作默认要求使用 master key

views/im-servermgmt-guide-python.md
=> feat: conversation class acl default value update

views/faq.md
thanks to @onerain88 for report
=> fix: update outdated link

views/custom-api-domain-guide.md, views/sdk_setup.tmpl
=> feat: update java sdk init usage

views/realtime-guide-senior.md
close https://github.com/leancloud/docs/issues/3246
=> fix(IM): signature implementation of swift & objc

views/leanstorage_guide.tmpl
=> fix: LiveQuery guide

views/ios_push_guide.md
close https://github.com/leancloud/docs/issues/3234
=> refactor(push): installation part of ios push guide

views/leanstorage_guide.tmpl
getThumbnailUrl -> getThumbUrl
Also make it more clear which parameter is width,
and which one is height.
=> fix(php): corrent thumbnail function name

views/realtime-guide-intermediate.md
=> feat(rtm): add code sample for custom msg attr

views/_helper.njk
OnMessageModified has been renamed to OnMessageUpdated.
=> fix(c#): update c# rtm event name

views/realtime-guide-senior.md
java-unified-sdk offers a new simplified overload
in 5.0.15:
https://github.com/leancloud/java-unified-sdk/commit/91c2050678e921c482efd825e356a8ec474fc396#diff-2ffb4d7ae5c87ac9c0bb206f3f30233fR323
=> fix(rtm): update createChatRoom usage sample

views/leanstorage_guide.tmpl
close https://github.com/leancloud/docs/issues/3285
=> Update leanstorage guide

templates/include/common-footer.html
Merging docs to LeanCloud in Google Analytics
=> Update the code of Google Analytics

views/leaninsight_guide.md
=> fix(js): update outdated api

views/sdk_setup.tmpl
=> feat(js): mention wechat mini-app component

views/leanengine_cloudfunction_guide.tmpl
=> feat(engine): beforeSave hook timeout workaround

views/leanengine_webhosting_guide.tmpl
=> fix(engine): LEANCLOUD_VERSION_TAG

templates/include/_apidocs.html
=> feat: link to Swift SDK API doc

views/leanstorage_guide.tmpl
=> fix(php): describe how to get object by id

views/kb-network-connectivity-diagnosis.md
=> feat: use nslookup for dig under Windows

views/leanstorage_guide.tmpl
=> refactor(storage_guide): add & update smaple code of swift

views/push_guide.md
=> chore(push): improve push docs

views/push_guide.md
> https://github.com/leancloud/avoscloud-push/issues/2299
=> feat(push) add push rest api argument

views/_helper.njk
=> fix(template): swift rtm variables

views/leanengine-web-frameworks.md, views/leanengine_webhosting_guide.tmpl
prepublish is deprecated
thanks to shifuchen98
=> fix(engine):  prepublish -> prepare

views/realtime-guide-beginner.md
=> chore(ios): briefly describe delegate

views/realtime-guide-beginner.md
=> fix(objc): delegate link to official doc instead

views/realtime-guide-intermediate.md
unified sdk removed AVIMMessageCreator
reported by [tinaL](https://forum.avoscloud.com/t/21960)
=> fix(java): custom msg type code sample update

views/im-servermgmt-guide-python.md, views/realtime-guide-beginner.md
to keep up with current SDK implementations.
=> fix(rtm): update unique default value description

custom/js/demo.js
Also update outdated qcloudShow properties.
=> Add new demo Funny Feed

views/weapp.md
- custom domain
- update rtm guide link
=> Weapp guide

views/leanstorage_guide.tmpl
Thank weak_ptr a lot for bringing this matter to our attention.
=> fix(python): wrong usage of user methods

views/realtime-guide-intermediate.md
to be consistent with examples of other SDKs
Thanks 宝梦科技 for bringing this matter to our attention.
=> feat(java): tweak msg setPushData example

views/leanengine_webhosting_guide.tmpl
Thank 517259854 for bringing this to our attention.
=> feat: windows does not have `eval`

templates/pages/index.html, views/realtime-guide-onoff-status.md
=> fix: update realtime guide onoff status

views/sdk_setup.tmpl
=> feat(sdk_setup): disable log of Objc & Swift SDK

views/realtime-guide-senior.md
=> fix(rtm): only rest use query history msg sign

views/rest_api.md
=> fix(rest): export data range uses updatedAt

templates/pages/faq_list.html, views/error_code.md, views/leanengine_faq.md
The connection limit is very permissive now.
=> fix(engine): update outdated 529 description

views/rest_api.md
see  also leancloud/docs-en#141
=> feat(rest): add File & GeoPoint, remove Relation

views/leanengine_faq.md
related forum post:
[21989](https://forum.leancloud.cn/t/topic/21989)
=> feat(engine): `lean init` without application

views/leanengine_cloudfunction_guide.tmpl, views/leanstorage_guide.tmpl
=> feat(hook): example for authData verification

views/rest_api.md
see also leancloud/docs-en#151
=> refactor(rest):merge GeoPoint queries into Queries

views/leanstorage_guide.tmpl, views/rest_api.md
=> feat(query): $size operator in rest & sdk

views/rest_sms_api.md
when using sms code to verify phone number
or reset password
close #3421
=> fix(rest): recommend also provide phone numebr

views/rest_api.md
=> feat(feedback): describe rest api result schema

views/sdk_setup.tmpl
=> fix(sdk): special gradle config for huawei push

views/leanstorage_guide.tmpl
=> fix(dashboard): AccessToken config UI update

views/push_guide.md
> https://github.com/leancloud/avoscloud-push/issues/2393
> https://github.com/leancloud/uluru-platform/pull/6089
现在在使用推送服务前要开启服务，增加了一段描述文字。
=> chore(push): remind users to turn it on before use push service

views/_data.njk, views/ios_push_guide.md, views/leaderboard-guide-dotnet.md, views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide.tmpl, views/leanstorage_guide.tmpl, views/multiplayer-guide-csharp.md, views/multiplayer-guide-js.md, views/multiplayer-quick-start-csharp.md, views/multiplayer-quick-start-js.md, views/multiplayer-server-quick-start-java.md, views/multiplayer.md, views/realtime-guide-beginner.md, views/weapp.md
=> fix(domian): more expilicit description

views/realtime-guide-intermediate.md
=> fix(rtm): objc custom key on custom msg

templates/pages/index.html, views/dot-notation.md, views/leanstorage_guide.tmpl, views/rest_api.md
=> feat: dot notation

views/rest_api.md
=> feat(rest): compress options

templates/pages/index.html, views/cdn-guide.md
Co-authored-by: jysperm <jysperm@gmail.com>
Co-authored-by: Jang Rush <weakish@gmail.com>
=> feat: cdn guide

views/ios_push_guide.md, views/push-faq.md, views/push_guide.md
=> Ios installation

views/leanstorage_guide.tmpl, views/multiplayer-guide-js.md, views/multiplayer-quick-start-js.md
Thanks to Hackensack and jansonhjx!
=> fix: typos

views/realtime-guide-systemconv.md
> https://github.com/leancloud/avoscloud-push/issues/2452
> https://github.com/leancloud/avoscloud-push/pull/2461
> https://github.com/leancloud/docs/pull/3482
修改用户【加入/离开】房间的 hook 名称
等 https://github.com/leancloud/avoscloud-push/pull/2461 合并测试完成后再合并这里
=> fix(rtm): rename member joined/left hooks to conversation added/removed

views/sdk_setup.tmpl
[对应的 SDK](https://github.com/leancloud/js-realtime-sdk/commit/0bc843e41349fbd0ec1829657a76b4ed7e9724c0) 已发布。
=> feat: 更新 JS IM SDK 的文件路径

views/leanengine_cli.md
=> feat(lean): brew network issue workarounds

views/sdk_setup.tmpl
请 @onerain88 帮忙确认下 .NET 的情况
请 @leeyeh 帮忙确认控制台 url 是否正确
=> Fix: .NET setup

views/kb_all_roducts_news.md
=> fix(news): change to relative links

views/leanstorage_guide.tmpl, views/sdk_setup.tmpl
- 用 `const` 代替 `var`
- 用箭头函数代替 `function`
- 用模版字符串代替 `+` 连接字符串
=> 更新「SDK 安装」、「数据存储」部分 JS 代码风格

views/leanstorage_guide.tmpl
https://github.com/leancloud/docs/commit/ecdc0c1c975e9c43c68b2a96ecee8920b9fa01d6 修改了小程序二维码图片的文件名。
=> fix(storage): QR code for LeanTodo

views/realtime-guide-beginner.md, views/realtime-guide-intermediate.md
=> refactor(rtm): receive custom msg type

templates/include/_apidocs.html, templates/include/doc-nav.html
see also leancloud/python-sdk#464
=> feat(python): update api doc link

views/leanengine_faq.md
=> feat(engine): quick batch deploy

views/deeplink.md, views/search-rest-api.md
- fix(search): wording
- feat(search): add internal links
=> wording & internal links

views/push_guide.md
close https://github.com/leancloud/uluru-platform/pull/6304
=> 补充 android channel id 参数

views/realtime-guide-beginner.md
=> feat(rtm): conv attrs in js, swift, objc, java

views/acl-guide.md
=> fix(acl): js role sample

views/leanstorage_guide.tmpl
and be consistent with other languages
see also #3527
=> fix(flutter): better and query example

views/realtime-guide-beginner.md
=> chore(rtm): link to sdk setup guide

views/leanstorage_guide.tmpl
Thanks to xbingo for asking this question.
=> feat(user):howto signup users with phone&password

views/rest_api.md
=> fix(rest): third party login refinement

views/leanstorage_guide.tmpl
=> fix template error

views/leanengine_cloudfunction_guide.tmpl
Thank [111938] for bringing this to our attention.
[111938]: https://forum.leancloud.cn/t/android-rpc/22880
=> fix(java): typo in callRPCInBackground sample

views/sms-guide.md
see also leancloud/docs-en#223
=> fix(sms): add missing dart code sample

views/leanengine_cloudfunction_guide.tmpl, views/leanstorage_guide.tmpl
cloudfunc has been renamed to cloud since 2.1.0
Thank [artsungames] for bringing this to our attention.
[artsungames]: https://forum.leancloud.cn/t/python-sdk/23021
=> fix(engine): python cloudfunc -> cloud

views/leanengine-rest-api.md
Add an example of passing sessionToken when invoking cloud functions.
=> feat(engine): x-lc-session

views/_data.njk, views/android_push_guide.md, views/error_code.md, views/ios_push_guide.md, views/push_guide.md
It seems combining strong mark and macro breaks table layout.
=> fix: nunjucks formatting error

templates/include/_apidocs.html
=> chore: php sdk api doc move to gh-pages

views/leanstorage_guide.tmpl, views/rest_api.md
添加苹果第三方登录
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api
=> (feat) add apple login

views/leanstorage_guide.tmpl
=> (fix) show swift code of apple sign in

views/leanstorage_guide.tmpl
Thank @sdjdd for bringing this to our attention.
=> fix(query): regexp query sample typos

views/sdk_setup.tmpl
来自[社区用户反馈](https://forum.leancloud.cn/t/flutter-sdk-message-query/23256/11)，文档 SDK 版本号有误。
=> fix-flutter-sdk-version

views/leanstorage_guide.tmpl
commit: https://github.com/leancloud/swift-sdk/pull/391/commits/7a4df106c5f9d9bbca0d6ffaf32bb2ac3128d3d4
提供更便利的 API
=> chore: upgrade swift sample code of apple sign in

views/rest_api.md
see also leancloud/docs-en#249
=> feat(acl): returnACL & role query

views/acl_guide_leanengine.md
Also:
- Update js sample according to recent versions of node.js sdk.
- Remove clinet-side object creation code for brevity.
see also leancloud/docs-en#250
=> feat(acl): add engine python, php, java sample

views/leanengine_webhosting_guide.tmpl
This reverts commit 016d1d56aa52338ddff323148965ae330bbca4fa.
=> Revert "feat(engine): intl. no fixed inbound IP"

views/realtime-guide-beginner.md
=> feat(rtm): warn direct write on _Conversation

views/leanstorage_guide.tmpl
=> feat(python): equvalent query constructing form

views/leanengine_cli.md
Thank 一点都不土 for bringing this to our attention.
=> feat(lean): chmod a+x

views/leanstorage_guide.tmpl
Thank Veryed for bringing this to our attention.
=> fix(java): PushService.startIfRequired position

views/leanengine_faq.md
=> feat(python): cloud function pointer

views/leanstorage_guide.tmpl
Its use cases are uncertain.
[zulip](https://zulip.lcops.cn/#narrow/stream/28-api/topic/livequery.20onlogin.20.E7.9A.84.E4.BD.BF.E7.94.A8.E5.9C.BA.E6.99.AF/near/2323811)
=> feat(livequery): remove login event

views/realtime-guide-beginner.md
社区用户反馈的示例代码有误： https://forum.leancloud.cn/t/topic/23540/3
=> fix-java-conversation-samplecode

views/status_system.md
=> fix(status): typos and refinements

views/_data.njk, views/leanstorage_guide.tmpl, views/rest_api.md
=> feat(file): query

views/leaderboard-guide-js.md
=> fix(leaderboard): get statistics without names

views/client-engine-guide-node.md
=> feat(game): client engine v1.0.0

views/sdk_setup.tmpl
Thank [CaptMichael] for bringing this to our attention.
[CaptMichael]: https://forum.leancloud.cn/t/leancloud-flutter-dio/23465/9?u=weakish
=> fix(flutter): storage sdk android permissions

views/custom-api-domain-guide.md
=> feat(domain): use `curl --resolve` to test ip

views/leanstorage_guide.tmpl, views/sms-guide.md
Improve wording to avoid ambiguilty.
see also leancloud/swift-sdk#403
=> fix(sms): wording

views/realtime-guide-beginner.md
close #3773
Thank [zshuang] & @zapcannon87
[zshuang]: https://forum.leancloud.cn/t/topic/23635/14
=> fix(rtm): typo in java code sample

views/leanengine_webhosting_guide.tmpl
- feat(engine): list php extensions
- feat(engine): not support path local repo
=> engine php local repo

views/acl-guide.md
related forum post: [23605](https://forum.leancloud.cn/t/livequery-acl/23605/)
=> fix(acl): using masterKey with LiveQuery

views/realtime-guide-beginner.md
=> feat(flutter): fetch from conversationMap first

templates/pages/faq_list.html
Developers can learn about recent news
from dashboard, blog, and forum.
=> feat(news): remove news section

views/leanstorage_guide.tmpl
in sample code of becomeWithSessionTokenInBackground
related ticket 36527
=> feat(java): introduce AVUser.changeCurrentUser

views/push_guide.md
=> fix(push):deviceProfile only supports equals query

views/app_search_guide.md
=> feat(search): js full text search highlight sample

views/leanengine_cloudfunction_guide.tmpl, views/leanstorage_guide.tmpl
- specify file key
- run remote cloud function
=> feat(php): sdk 0.14.0 updates

views/cql_guide.md
=> fix(cql): geopoint query limit: no count support

views/error_code.md
=> feat(engine): Application not found error

views/leanengine_webhosting_guide.tmpl
to detect orginal request protocol
=> feat(engine): use X-Forwarded-Proto

views/realtime-guide-intermediate.md
related forum post: [23703]
[23703]: https://forum.leancloud.cn/t/prod-prod/23703/
=> feat(rtm): _profile not apply to iOS token auth

templates/include/_apidocs.html, views/sdk_setup-go.md, views/sdk_setup.tmpl, views/start.md
=> ✨ Add sdk_setup-go

views/leanstorage_friendship_guide.md
=> feat: csharp friend

views/leanstorage_guide.tmpl
Thank [tom200989] for bringing this to our attention.
[tom200989]: https://www.reddit.com/r/LeanCloud/comments/kx48t1/
=> fix(java): typo

views/_rtm_rest_api_v2_chatroom.njk, views/_rtm_rest_api_v2_normal.njk
in the section of query conversation history messages.
Thank [
LifeCycling] for bringing this to our attention.
[LifeCycling]: https://forum.leancloud.cn/t/topic/16875/8
=> chore: mention query all history msg of app

views/relation-guide.md
Also some Python code styling tweaks.
(Python community prefers snake_case.)
=> feat: php code sample

views/realtime-guide-intermediate.md
=> chore: clarify how to reset badge

views/android_push_guide.md, views/flutter_push_guide.md
=> fix(flutter): android push setup

views/leanstorage_guide.tmpl
=> feat(user): associateWithAuthData

views/_rtm_rest_api_v2_client.njk
=> chore(rtm): /rtm/clients/sign is not idempotent

custom/js/app.js, templates/include/header.html
Partially fix #3804
完整的方案是把 docs 的部署从 leancloud.cn 切到单独的 docs.leancloud.cn。不过先把 console-api 切过去修复失效的功能。
=> feat: use different console-api for different regions

views/realtime-guide-systemconv.md
Thank [469073411] for bringing this to our attention.
[469073411]: https://forum.leancloud.cn/t/python-hook/24037/
=> fix(rtm): _messageReceived sample error

views/weapp.md
=> feat(user): upstream wx.login update

views/leanengine_cloudfunction_guide.tmpl, views/leanengine_webhosting_guide.tmpl, views/realtime-guide-systemconv.md
匹配 [新版 SDK](https://github.com/leancloud/csharp-sdk/releases/tag/0.7.1) 的使用指南
=> 新版 C# 云引擎文档

views/realtime-guide-intermediate.md
=> fix: _profile does appliest to cert based ios push

views/leanstorage_guide.tmpl, views/rest_api.md
=> fix(user): more details on uid

views/dot-notation.md
=> fix: clarify pointer dot notation

views/leanstorage_guide.tmpl
Thank [Riber] for bringing this to our attention.
[Riber]: https://forum.leancloud.cn/t/topic/24141/
=> feat(js): more detailed batch sample

views/leanstorage-faq.md, views/sdk_setup.tmpl
Android 混淆代码放在 SDK 初始化页面。
[Slack沟通记录](https://xindong.slack.com/archives/C01F5M8NDDX/p1619160153131800?thread_ts=1616137721.006000&cid=C01F5M8NDDX)
=> move android proguard to sdk setup

templates/include/doc-nav.html, templates/pages/index.html, views/leandb_mongo_guide.md
=> ✨ Add LeanDB MongoDB

views/leanengine_cloudfunction_guide.tmpl
Thank @onerain88 for bringing this to our attention.
=> fix(java): typos in code sample

views/leanengine_faq.md
related ticket: 37355
Co-authored-by: Jang Rush <weakish@gmail.com>
=> feat: engine response slow faq

views/leanstorage_guide.tmpl
=> feat: get access token using master key

views/leanstorage_guide.tmpl
=> feat: flutter apple sigin in sample

views/realtime-guide-intermediate.md
js sdk [不再支持](https://github.com/leancloud/js-realtime-sdk/releases/tag/v5.0.0-rc.6)「推」的模式。
=> feat: update unread message mode of js sdk

custom/js/demo.js
=> remove feedback demo url

views/leanstorage-started-objc.md, views/leanstorage_guide-objc.md, views/leanstorage_guide.tmpl
=> feat(objc): update leanstorage guide

views/leanstorage_friendship_guide.md
=> feat(objc): update friendship guide

views/relation-guide.md
=> feat(objc): update relation guide

templates/include/doc-nav.html
Thank fangxing for bringing this to our attention.
=> fix: update php sdk api link

views/leanstorage_guide-dotnet.md, views/leanstorage_guide-java.md, views/leanstorage_guide-objc.md, views/leanstorage_guide.tmpl
Thank kangjiawei for bringing this to our attention.
=> fix: show how to get file url

views/leaderboard-quick-start-js.md, views/leanstorage_guide.tmpl, views/sdk_setup.tmpl, views/sms-guide.md
since jsdelivr may soon have connection issues in some regions
=> fix: replace jsdelivr with bdstatic

views/sdk_setup.tmpl
Thank [1111015] for bringing this to our attention.
[1111015]: https://forum.leancloud.cn/t/flutter-sdk/24442/3
=> fix: typo in java sdk setup code

views/sdk_setup.tmpl
https://www.leanticket.cn/tickets/38274
=> Fix dead code.bdstatic.com links

views/error_code.md
=> fix: error code links

views/leaderboard-rest-api.md
user 和 object 的排行榜中的参数改动：
* 从 selectUserKeys/selectObjectKeys 改为 selectKeys
* 从 includeUser/includeObject 改为 includeKeys
=> (chore) change params of leaderboard endpoints.

templates/include/doc-nav.html, templates/pages/index.html
Thank @liuchong for bringing this to our attention.
=> fix: remove dead links

templates/pages/index.html
- 「聊天机器人」在 #4006 以及 #4007 讨论过，此处遗漏未删，补个🔪。
- 「为网站加入收款功能」原内容已删 #3924，这里的链接一起删掉吧 。
=> fix: remove outdated content and dead link

views/sdk_setup.tmpl
=> fix(js/im): remove outdated tip

views/leanstorage_friendship_guide.md
=> add API for delete friendshipRequest

views/sdk_setup-dotnet-standard.md
see also: https://github.com/leancloud/csharp-sdk/pull/188
=> feat: C# SDK version bump 0.10.0

views/leanstorage_guide-objc.md
https://github.com/leancloud/objc-sdk/releases/tag/13.6.0
=> refactor: storage guide objc

views/account-and-dashboard-faq.md
related slack discussion:
https://xindong.slack.com/archives/C01S9A1B4GK/p1636096235060500?thread_ts=1636095992.059900&cid=C01S9A1B4GK
=> feat: sdk data collection faq

views/leanstorage_guide-java.md
slack:
https://xindong.slack.com/archives/C01HZ8BS7PT/p1636104346085300
=> fix: java loginWithAuthData sample

views/leanengine_quickstart.md, views/leanstorage_guide.tmpl
=> fix: go Create typo

views/android_mixpush_guide.md, views/push-rest-api.md
Thank [Nick] for bringing this to our attention.
[Nick]: https://xindong.slack.com/archives/C01F5M8NDDX/p1637569030045300?thread_ts=1636964045.031300&cid=C01F5M8NDDX
=> fix: typo in push query

views/rest_api.md
Thank 136975643 for bringing this to our attention.
[136975643]: https://forum.leancloud.cn/t/rest-api-include/24818
=> fix: __type of included pointer is still Pointer

views/leanengine_webhosting_guide.tmpl
see also leancloud/lean-cli#485
=> feat: lean-cli now supports `lean up`

views/push-rest-api.md
=> 更新一下推送接口关于 action 参数的说明

views/push-rest-api.md
Co-authored-by: liuchong <mail@liuchong.io>
Thank Nick for bringing this to our attention.
=> feat: rest api push response

views/rest_api.md
Thank [wim] for bringing this to our attention.
[wim]: https://forum.leancloud.cn/t/restapi-x-lc-sign-401/22892/
=> fix: md5 sign need to use lowercase letters

views/acl-guide.md
这里文字内容和实际有出入。
文字下面对应的截图是正确的，所以只改了文字。
=> Draft: fix: default acl restricts write

views/_helper.njk, views/realtime-guide-beginner.md
=> fix: objc rtm self left event is different

views/android_mixpush_guide.md
[OPPO 开发者文档](https://open.oppomobile.com/wiki/doc#id=11050) 提供最新 3.0.0 版本 aar 文件下载地址是：https://openfs.oppomobile.com/open/oop/202109/18/a6165ca79f20025a21a8158a30dd6964.zip
=> update oppo download url

templates/include/doc-nav.html
suggested by fengbolin
slack:
https://xindong.slack.com/archives/C01S9A1B4GK/p1640604452212800?thread_ts=1640596528.210200&cid=C01S9A1B4GK
=> feat: remove js push guide link

views/leanstorage_friendship_guide.md
* 增加获取互关列表的接口
* 给 friendship 接口加上 sessionToken
=> (feat) add mutualFollowees endpoint and add sessionToken to friendship REST API.

views/leanengine_cli.md
slack: https://xindong.slack.com/archives/C01S89MAHTL/p1644477483197949
=> fix: AUR lean-cli-git not work

views/sdk_setup-dotnet-standard.md
https://github.com/leancloud/csharp-sdk/pull/196
=> feat: C# SDK version bump 0.10.2

views/android_mixpush_guide.md, views/android_push_guide.md, views/sdk_setup-java.md
=> feat: update java sdk version to 8.2.5

views/sdk_setup-dotnet-standard.md
https://github.com/leancloud/csharp-sdk/pull/203
=> feat: C# SDK version bump 0.10.5

views/leanstorage_friendship_guide.md
https://forum.leancloud.cn/t/java-avuser/25114
=> fix(friendship): code samples

views/sdk_setup-dotnet-standard.md
https://github.com/leancloud/csharp-sdk/pull/207
=> feat: C# SDK version bump 0.10.7

templates/include/doc-nav.html, templates/pages/index.html
上下文：
https://xindong.slack.com/archives/C01S9A1B4GK/p1652945251291909
=> fix(engine): update LeanEngine docs links

views/leanstorage_guide-dotnet.md, views/leanstorage_guide-java.md, views/leanstorage_guide-objc.md, views/leanstorage_guide.tmpl
=> fix: remove redundant words

templates/pages/faq_list.html, templates/pages/index.html
=> Revert "fix(domain): update links to domain docs"

templates/include/doc-nav.html, templates/pages/index.html, views/start.md
=> Revert "fix(storage): update links to storage docs"

views/rest_api.md
[工单](https://www.leanticket.cn/tickets/40294)
=> chore(REST API)：delete several objects in one request

views/multiplayer-guide.tmpl
[讨论](https://xindong.slack.com/archives/C01S8E7PVC3/p1667897473200129)
=> fix: play kick event

views/push-faq.md
[文档链接](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc)
=> add iOS push faq

templates/include/doc-nav.html, templates/pages/index.html
数据存储 和 推送 大部分内容已经添加到[新文档](https://docs.leancloud.cn/sdk/storage/overview/)，更新一下旧文档首页链接。
@SXiaoXu @yuwenjian
=> chore: update links to the new site

templates/include/doc-nav.html, templates/pages/index.html
https://xindong.slack.com/archives/C01EN4GRJQP/p1678957958483469
=> chore(dashboard): update links
